/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	v1 "sigs.k8s.io/gateway-api/apis/applyconfiguration/apis/v1"
	apisv1 "sigs.k8s.io/gateway-api/apis/v1"
	v1alpha2 "sigs.k8s.io/gateway-api/apis/v1alpha2"
)

// BackendTLSPolicyConfigApplyConfiguration represents an declarative configuration of the BackendTLSPolicyConfig type for use
// with apply.
type BackendTLSPolicyConfigApplyConfiguration struct {
	CACertRefs       []v1.LocalObjectReferenceApplyConfiguration `json:"caCertRefs,omitempty"`
	WellKnownCACerts *v1alpha2.WellKnownCACertType               `json:"wellKnownCACerts,omitempty"`
	Hostname         *apisv1.PreciseHostname                     `json:"hostname,omitempty"`
}

// BackendTLSPolicyConfigApplyConfiguration constructs an declarative configuration of the BackendTLSPolicyConfig type for use with
// apply.
func BackendTLSPolicyConfig() *BackendTLSPolicyConfigApplyConfiguration {
	return &BackendTLSPolicyConfigApplyConfiguration{}
}

// WithCACertRefs adds the given value to the CACertRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CACertRefs field.
func (b *BackendTLSPolicyConfigApplyConfiguration) WithCACertRefs(values ...*v1.LocalObjectReferenceApplyConfiguration) *BackendTLSPolicyConfigApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithCACertRefs")
		}
		b.CACertRefs = append(b.CACertRefs, *values[i])
	}
	return b
}

// WithWellKnownCACerts sets the WellKnownCACerts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WellKnownCACerts field is set to the value of the last call.
func (b *BackendTLSPolicyConfigApplyConfiguration) WithWellKnownCACerts(value v1alpha2.WellKnownCACertType) *BackendTLSPolicyConfigApplyConfiguration {
	b.WellKnownCACerts = &value
	return b
}

// WithHostname sets the Hostname field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Hostname field is set to the value of the last call.
func (b *BackendTLSPolicyConfigApplyConfiguration) WithHostname(value apisv1.PreciseHostname) *BackendTLSPolicyConfigApplyConfiguration {
	b.Hostname = &value
	return b
}
