/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	v1 "sigs.k8s.io/gateway-api/apis/v1"
)

// PolicyTargetReferenceWithSectionNameApplyConfiguration represents an declarative configuration of the PolicyTargetReferenceWithSectionName type for use
// with apply.
type PolicyTargetReferenceWithSectionNameApplyConfiguration struct {
	PolicyTargetReferenceApplyConfiguration `json:",inline"`
	SectionName                             *v1.SectionName `json:"sectionName,omitempty"`
}

// PolicyTargetReferenceWithSectionNameApplyConfiguration constructs an declarative configuration of the PolicyTargetReferenceWithSectionName type for use with
// apply.
func PolicyTargetReferenceWithSectionName() *PolicyTargetReferenceWithSectionNameApplyConfiguration {
	return &PolicyTargetReferenceWithSectionNameApplyConfiguration{}
}

// WithGroup sets the Group field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Group field is set to the value of the last call.
func (b *PolicyTargetReferenceWithSectionNameApplyConfiguration) WithGroup(value v1.Group) *PolicyTargetReferenceWithSectionNameApplyConfiguration {
	b.Group = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *PolicyTargetReferenceWithSectionNameApplyConfiguration) WithKind(value v1.Kind) *PolicyTargetReferenceWithSectionNameApplyConfiguration {
	b.Kind = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *PolicyTargetReferenceWithSectionNameApplyConfiguration) WithName(value v1.ObjectName) *PolicyTargetReferenceWithSectionNameApplyConfiguration {
	b.Name = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *PolicyTargetReferenceWithSectionNameApplyConfiguration) WithNamespace(value v1.Namespace) *PolicyTargetReferenceWithSectionNameApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithSectionName sets the SectionName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SectionName field is set to the value of the last call.
func (b *PolicyTargetReferenceWithSectionNameApplyConfiguration) WithSectionName(value v1.SectionName) *PolicyTargetReferenceWithSectionNameApplyConfiguration {
	b.SectionName = &value
	return b
}
