apiVersion: gateway.networking.kubernetes.io/v1
kind: ImplementationListDetails
organization: nginx
project: nginx-gateway-fabric
fullName: NGINX Gateway Fabric
description: |
  [NGINX Gateway Fabric][nginx-gateway-fabric] is an open-source project that provides an implementation of the Gateway API using [NGINX][nginx] as the data plane. The goal of this project is to implement the core Gateway API to configure an HTTP or TCP/UDP load balancer, reverse-proxy, or API gateway for applications running on Kubernetes. You can find the comprehensive NGINX Gateway Fabric user documentation on the [NGINX Documentation][nginx-docs] website.

  For a list of supported Gateway API resources and features, see the [Gateway API Compatibility][nginx-compat] doc.

  If you have any suggestions or experience issues with NGINX Gateway Fabric, please [create an issue][nginx-issue-new] or a [discussion][nginx-disc-new] on GitHub. You can also ask for help in the [NGINX Community Forum][nginx-forum].

  [nginx-gateway-fabric]: https://github.com/nginx/nginx-gateway-fabric
  [nginx]: https://nginx.org/
  [nginx-docs]: https://docs.nginx.com/nginx-gateway-fabric/
  [nginx-compat]: https://docs.nginx.com/nginx-gateway-fabric/overview/gateway-api-compatibility/
  [nginx-issue-new]: https://github.com/nginx/nginx-gateway-fabric/issues/new
  [nginx-disc-new]: https://github.com/nginx/nginx-gateway-fabric/discussions/new
  [nginx-forum]: https://community.nginx.org/
