/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha2 "sigs.k8s.io/gateway-api/apis/v1alpha2"
	scheme "sigs.k8s.io/gateway-api/pkg/client/clientset/versioned/scheme"
)

// CustomGRPCRoutesGetter has a method to return a CustomGRPCRouteInterface.
// A group's client should implement this interface.
type CustomGRPCRoutesGetter interface {
	CustomGRPCRoutes(namespace string) CustomGRPCRouteInterface
}

// CustomGRPCRouteInterface has methods to work with CustomGRPCRoute resources.
type CustomGRPCRouteInterface interface {
	Create(ctx context.Context, customGRPCRoute *v1alpha2.CustomGRPCRoute, opts v1.CreateOptions) (*v1alpha2.CustomGRPCRoute, error)
	Update(ctx context.Context, customGRPCRoute *v1alpha2.CustomGRPCRoute, opts v1.UpdateOptions) (*v1alpha2.CustomGRPCRoute, error)
	UpdateStatus(ctx context.Context, customGRPCRoute *v1alpha2.CustomGRPCRoute, opts v1.UpdateOptions) (*v1alpha2.CustomGRPCRoute, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha2.CustomGRPCRoute, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha2.CustomGRPCRouteList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.CustomGRPCRoute, err error)
	CustomGRPCRouteExpansion
}

// customGRPCRoutes implements CustomGRPCRouteInterface
type customGRPCRoutes struct {
	client rest.Interface
	ns     string
}

// newCustomGRPCRoutes returns a CustomGRPCRoutes
func newCustomGRPCRoutes(c *GatewayV1alpha2Client, namespace string) *customGRPCRoutes {
	return &customGRPCRoutes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the customGRPCRoute, and returns the corresponding customGRPCRoute object, and an error if there is any.
func (c *customGRPCRoutes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha2.CustomGRPCRoute, err error) {
	result = &v1alpha2.CustomGRPCRoute{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("customgrpcroutes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CustomGRPCRoutes that match those selectors.
func (c *customGRPCRoutes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha2.CustomGRPCRouteList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha2.CustomGRPCRouteList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("customgrpcroutes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested customGRPCRoutes.
func (c *customGRPCRoutes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("customgrpcroutes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a customGRPCRoute and creates it.  Returns the server's representation of the customGRPCRoute, and an error, if there is any.
func (c *customGRPCRoutes) Create(ctx context.Context, customGRPCRoute *v1alpha2.CustomGRPCRoute, opts v1.CreateOptions) (result *v1alpha2.CustomGRPCRoute, err error) {
	result = &v1alpha2.CustomGRPCRoute{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("customgrpcroutes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(customGRPCRoute).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a customGRPCRoute and updates it. Returns the server's representation of the customGRPCRoute, and an error, if there is any.
func (c *customGRPCRoutes) Update(ctx context.Context, customGRPCRoute *v1alpha2.CustomGRPCRoute, opts v1.UpdateOptions) (result *v1alpha2.CustomGRPCRoute, err error) {
	result = &v1alpha2.CustomGRPCRoute{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("customgrpcroutes").
		Name(customGRPCRoute.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(customGRPCRoute).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *customGRPCRoutes) UpdateStatus(ctx context.Context, customGRPCRoute *v1alpha2.CustomGRPCRoute, opts v1.UpdateOptions) (result *v1alpha2.CustomGRPCRoute, err error) {
	result = &v1alpha2.CustomGRPCRoute{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("customgrpcroutes").
		Name(customGRPCRoute.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(customGRPCRoute).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the customGRPCRoute and deletes it. Returns an error if one occurs.
func (c *customGRPCRoutes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("customgrpcroutes").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *customGRPCRoutes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("customgrpcroutes").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched customGRPCRoute.
func (c *customGRPCRoutes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.CustomGRPCRoute, err error) {
	result = &v1alpha2.CustomGRPCRoute{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("customgrpcroutes").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
