apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    api-approved.kubernetes.io: https://github.com/kubernetes-sigs/gateway-api/pull/3328
    gateway.networking.k8s.io/bundle-version: v1.2.1
    gateway.networking.k8s.io/channel: experimental
  creationTimestamp: null
  name: udproutes.gateway.networking.k8s.io
spec:
  group: gateway.networking.k8s.io
  names:
    categories:
    - gateway-api
    kind: UDPRoute
    listKind: UDPRouteList
    plural: udproutes
    singular: udproute
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha2
    schema:
      openAPIV3Schema:
        description: |-
          UDPRoute provides a way to route UDP traffic. When combined with a Gateway
          listener, it can be used to forward traffic on the port specified by the
          listener to a set of backends specified by the UDPRoute.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            $ref: '#/definitions/sigs.k8s.io~1gateway-api~1apis~1v1~0CommonRouteSpec'
            description: Spec defines the desired state of UDPRoute.
            properties:
              rules:
                description: Rules are a list of UDP matchers and actions.
                items:
                  description: UDPRouteRule is the configuration for a given rule.
                  properties:
                    backendRefs:
                      description: |-
                        BackendRefs defines the backend(s) where matching requests should be
                        sent. If unspecified or invalid (refers to a nonexistent resource or a
                        Service with no endpoints), the underlying implementation MUST actively
                        reject connection attempts to this backend. Packet drops must
                        respect weight; if an invalid backend is requested to have 80% of
                        the packets, then 80% of packets must be dropped instead.

                        Support: Core for Kubernetes Service

                        Support: Extended for Kubernetes ServiceImport

                        Support: Implementation-specific for any other resource

                        Support for weight: Extended
                      items:
                        $ref: '#/definitions/sigs.k8s.io~1gateway-api~1apis~1v1~0BackendRef'
                      maxItems: 16
                      minItems: 1
                      type: array
                    name:
                      $ref: '#/definitions/sigs.k8s.io~1gateway-api~1apis~1v1~0SectionName'
                      description: |-
                        Name is the name of the route rule. This name MUST be unique within a Route if it is set.

                        Support: Extended
                  type: object
                maxItems: 16
                minItems: 1
                type: array
                x-kubernetes-validations:
                - message: Rule name must be unique within the route
                  rule: self.all(l1, !has(l1.name) || self.exists_one(l2, has(l2.name)
                    && l1.name == l2.name))
            required:
            - rules
            type: object
          status:
            $ref: '#/definitions/sigs.k8s.io~1gateway-api~1apis~1v1~0RouteStatus'
            description: Status defines the current state of UDPRoute.
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
