/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	apisxv1alpha1 "sigs.k8s.io/gateway-api/apisx/applyconfiguration/apisx/v1alpha1"
	v1alpha1 "sigs.k8s.io/gateway-api/apisx/v1alpha1"
	scheme "sigs.k8s.io/gateway-api/pkg/clientx/clientset/versioned/scheme"
)

// ListenerSetsGetter has a method to return a ListenerSetInterface.
// A group's client should implement this interface.
type ListenerSetsGetter interface {
	ListenerSets(namespace string) ListenerSetInterface
}

// ListenerSetInterface has methods to work with ListenerSet resources.
type ListenerSetInterface interface {
	Create(ctx context.Context, listenerSet *v1alpha1.ListenerSet, opts v1.CreateOptions) (*v1alpha1.ListenerSet, error)
	Update(ctx context.Context, listenerSet *v1alpha1.ListenerSet, opts v1.UpdateOptions) (*v1alpha1.ListenerSet, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, listenerSet *v1alpha1.ListenerSet, opts v1.UpdateOptions) (*v1alpha1.ListenerSet, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ListenerSet, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ListenerSetList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ListenerSet, err error)
	Apply(ctx context.Context, listenerSet *apisxv1alpha1.ListenerSetApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.ListenerSet, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, listenerSet *apisxv1alpha1.ListenerSetApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.ListenerSet, err error)
	ListenerSetExpansion
}

// listenerSets implements ListenerSetInterface
type listenerSets struct {
	*gentype.ClientWithListAndApply[*v1alpha1.ListenerSet, *v1alpha1.ListenerSetList, *apisxv1alpha1.ListenerSetApplyConfiguration]
}

// newListenerSets returns a ListenerSets
func newListenerSets(c *GatewayV1alpha1Client, namespace string) *listenerSets {
	return &listenerSets{
		gentype.NewClientWithListAndApply[*v1alpha1.ListenerSet, *v1alpha1.ListenerSetList, *apisxv1alpha1.ListenerSetApplyConfiguration](
			"listenersets",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.ListenerSet { return &v1alpha1.ListenerSet{} },
			func() *v1alpha1.ListenerSetList { return &v1alpha1.ListenerSetList{} }),
	}
}
