kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: shared-gateway
  namespace: infra-ns
spec:
  gatewayClassName: acme-lb
  listeners:  
  - hostname: "foo.example.com"
    protocol: HTTP
    port: 80
    routes:
      kind: HTTPRoute
      namespaces:
        from: "All"
