/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	apisxv1alpha1 "sigs.k8s.io/gateway-api/apisx/v1alpha1"
)

// XBackendLister helps list XBackends.
// All objects returned here must be treated as read-only.
type XBackendLister interface {
	// List lists all XBackends in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apisxv1alpha1.XBackend, err error)
	// XBackends returns an object that can list and get XBackends.
	XBackends(namespace string) XBackendNamespaceLister
	XBackendListerExpansion
}

// xBackendLister implements the XBackendLister interface.
type xBackendLister struct {
	listers.ResourceIndexer[*apisxv1alpha1.XBackend]
}

// NewXBackendLister returns a new XBackendLister.
func NewXBackendLister(indexer cache.Indexer) XBackendLister {
	return &xBackendLister{listers.New[*apisxv1alpha1.XBackend](indexer, apisxv1alpha1.Resource("xbackend"))}
}

// XBackends returns an object that can list and get XBackends.
func (s *xBackendLister) XBackends(namespace string) XBackendNamespaceLister {
	return xBackendNamespaceLister{listers.NewNamespaced[*apisxv1alpha1.XBackend](s.ResourceIndexer, namespace)}
}

// XBackendNamespaceLister helps list and get XBackends.
// All objects returned here must be treated as read-only.
type XBackendNamespaceLister interface {
	// List lists all XBackends in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apisxv1alpha1.XBackend, err error)
	// Get retrieves the XBackend from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apisxv1alpha1.XBackend, error)
	XBackendNamespaceListerExpansion
}

// xBackendNamespaceLister implements the XBackendNamespaceLister
// interface.
type xBackendNamespaceLister struct {
	listers.ResourceIndexer[*apisxv1alpha1.XBackend]
}
