/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	apisxv1alpha1 "sigs.k8s.io/gateway-api/apisx/v1alpha1"
)

// XTelemetryPolicyLister helps list XTelemetryPolicies.
// All objects returned here must be treated as read-only.
type XTelemetryPolicyLister interface {
	// List lists all XTelemetryPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apisxv1alpha1.XTelemetryPolicy, err error)
	// XTelemetryPolicies returns an object that can list and get XTelemetryPolicies.
	XTelemetryPolicies(namespace string) XTelemetryPolicyNamespaceLister
	XTelemetryPolicyListerExpansion
}

// xTelemetryPolicyLister implements the XTelemetryPolicyLister interface.
type xTelemetryPolicyLister struct {
	listers.ResourceIndexer[*apisxv1alpha1.XTelemetryPolicy]
}

// NewXTelemetryPolicyLister returns a new XTelemetryPolicyLister.
func NewXTelemetryPolicyLister(indexer cache.Indexer) XTelemetryPolicyLister {
	return &xTelemetryPolicyLister{listers.New[*apisxv1alpha1.XTelemetryPolicy](indexer, apisxv1alpha1.Resource("xtelemetrypolicy"))}
}

// XTelemetryPolicies returns an object that can list and get XTelemetryPolicies.
func (s *xTelemetryPolicyLister) XTelemetryPolicies(namespace string) XTelemetryPolicyNamespaceLister {
	return xTelemetryPolicyNamespaceLister{listers.NewNamespaced[*apisxv1alpha1.XTelemetryPolicy](s.ResourceIndexer, namespace)}
}

// XTelemetryPolicyNamespaceLister helps list and get XTelemetryPolicies.
// All objects returned here must be treated as read-only.
type XTelemetryPolicyNamespaceLister interface {
	// List lists all XTelemetryPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apisxv1alpha1.XTelemetryPolicy, err error)
	// Get retrieves the XTelemetryPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apisxv1alpha1.XTelemetryPolicy, error)
	XTelemetryPolicyNamespaceListerExpansion
}

// xTelemetryPolicyNamespaceLister implements the XTelemetryPolicyNamespaceLister
// interface.
type xTelemetryPolicyNamespaceLister struct {
	listers.ResourceIndexer[*apisxv1alpha1.XTelemetryPolicy]
}
