version: 2
updates:
  # Dependencies listed in go.mod
  - package-ecosystem: "gomod"
    directories:
    - "/"
    - "/site"
    schedule:
      interval: "weekly"
    groups:
      non-k8s:
        patterns:
          - "*"
        exclude-patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
      k8s.io: # Group k8s.io golang dependencies updates
          patterns:
            - "k8s.io/*"
            - "sigs.k8s.io/*"
    labels:
      - go
      - dependencies
      - ok-to-test
      - release-note-none

  # Images listed in Dockerfile or Kubernetes manifests
  - package-ecosystem: "docker"
    directories:
      - "/conformance/base"
      - "/conformance/mesh"
      - "/conformance/tests"
      - "/conformance/tests/mesh"
    schedule:
      interval: "daily"
    groups:
      gateway-api-conformance:
        patterns:
          - "registry.k8s.io/gateway-api/conformance/*"
    labels:
      - docker
      - dependencies
      - ok-to-test
      - release-note-none

  #  Github actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "release-note-none"
      - "ok-to-test"

  # Dependencies listed in site/package.json
  - package-ecosystem: "npm"
    directory: "/site"
    schedule:
      interval: "weekly"
    labels:
      - javascript
      - dependencies
      - ok-to-test
      - release-note-none


