apiVersion: gateway.networking.kubernetes.io/v1
kind: ImplementationListDetails
organization: kgateway-dev
project: kgateway
fullName: kgateway
description: |
  The [kgateway] project is a feature-rich, Kubernetes-native ingress controller and next-generation API gateway.
  It is focused on maintaining a great HTTP experience, extending features for advanced routing in scenarios such as AI and MCP gateways, and interoperating with a service mesh such as Istio in both ambient and sidecar modes.
  This focus means that you can easily configure a set of Envoy instances that are reasonably distributed in a performant way across many north-south and east-west use cases.

  Kgateway is generally available with its 2.0 release.

  [kgateway]:https://kgateway.dev/docs
