version: v2.7.0
name: golangci-kube-api-linter
destination: ./bin
plugins:
- module: 'sigs.k8s.io/kube-api-linter'
  version: 'v0.0.0-20251201121224-8e86c463aeb8' # Pin to a commit while there's no tag
