# Netlify build instructions
[build]
    command = "pip install -r hack/mkdocs/image/requirements.txt && cd site && npm install && cd .. && make build-docs-netlify"
    publish = "site/public"

[build.environment]
    PYTHON_VERSION = "3.12"
    GO_VERSION = "1.24.1"
    # node Active LTS
    NODE_VERSION = "20.20.0"
    HUGO_VERSION = "0.148.0"

# Standard Netlify redirects
[[redirects]]
    from = "https://main--kubernetes-sigs-gateway-api.netlify.com/*"
    to = "https://main.gateway-api.sigs.k8s.io/:splat"
    status = 301
    force = true

# HTTP-to-HTTPS rules
[[redirects]]
    from = "http://main.gateway-api.sigs.k8s.io/*"
    to = "https://main.gateway-api.sigs.k8s.io/:splat"
    status = 301
    force = true

[[redirects]]
    from = "http://main--kubernetes-sigs-gateway-api.netlify.com/*"
    to = "http://main.gateway-api.sigs.k8s.io/:splat"
    status = 301
    force = true

[[redirects]]
    from = "/geps/gep-1426"
    to = "/geps/gep-1294"
    status = 301
    force = true
