apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  name: prod-web
spec:
  gatewayClassName: acme-lb
  listeners:  
  - protocol: HTTP
    port: 80
    routes:
      namespaces:
      - selector:
          matchLabels:
            gateway: prod-web-gw
      kinds:
      - kind: HTTPRoute
