# Used in
# - site-src/v1alpha2/guides/multiple-ns.md
# - site-src/v1alpha2/guides/traffic-splitting.md
# - site-src/v1alpha2/guides/http-routing.md
# - site-src/v1alpha2/guides/tls.md
# - site-src/v1alpha2/guides/simple-gateway.md

apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  name: prod-web
spec:
  gatewayClassName: acme-lb
  listeners:  
  - protocol: HTTP
    port: 80
    name: prod-web-gw
    allowedRoutes:
      namespaces:
        from: Same
