apiVersion: gateway.networking.k8s.io/v1
date: "2026-01-30T13:31:15-06:00"
gatewayAPIChannel: standard
gatewayAPIVersion: v1.4.0
implementation:
  contact:
  - team-devex@graviteesource.com
  organization: gravitee.io
  project: gravitee-kubernetes-operator
  url: https://github.com/gravitee-io/gravitee-kubernetes-operator
  version: 4.10.3
kind: ConformanceReport
mode: default
profiles:
- core:
    result: partial
    skippedTests:
    - HTTPRouteMatchingAcrossRoutes
    statistics:
      Failed: 0
      Passed: 32
      Skipped: 1
  extended:
    result: success
    statistics:
      Failed: 0
      Passed: 7
      Skipped: 0
    supportedFeatures:
    - GatewayPort8080
    - HTTPRoutePathRedirect
    - HTTPRoutePathRewrite
    - HTTPRoutePortRedirect
    - HTTPRouteResponseHeaderModification
    - HTTPRouteSchemeRedirect
    unsupportedFeatures:
    - GatewayAddressEmpty
    - GatewayHTTPListenerIsolation
    - GatewayInfrastructurePropagation
    - GatewayStaticAddresses
    - HTTPRouteBackendProtocolH2C
    - HTTPRouteBackendProtocolWebSocket
    - HTTPRouteBackendRequestHeaderModification
    - HTTPRouteBackendTimeout
    - HTTPRouteCORS
    - HTTPRouteDestinationPortMatching
    - HTTPRouteHostRewrite
    - HTTPRouteMethodMatching
    - HTTPRouteNamedRouteRule
    - HTTPRouteParentRefPort
    - HTTPRouteQueryParamMatching
    - HTTPRouteRequestMirror
    - HTTPRouteRequestMultipleMirrors
    - HTTPRouteRequestPercentageMirror
    - HTTPRouteRequestTimeout
  name: GATEWAY-HTTP
  summary: Core tests partially succeeded with 1 test skips. Extended tests succeeded.
