apiVersion: gateway.networking.k8s.io/v1
date: "2026-09-09T00:10:57-04:00"
gatewayAPIChannel: standard
gatewayAPIVersion: v1.6.2
implementation:
  contact:
  - gateway-api@buoyant.io
  organization: Buoyant
  project: Buoyant Enterprise for Linkerd
  url: https://buoyant.io/
  version: enterprise-2.20.2
kind: ConformanceReport
mode: default
profiles:
- core:
    result: partial
    skippedTests:
    - MeshGRPCRouteRequestHeaderModifier
    statistics:
      Failed: 0
      Passed: 2
      Skipped: 1
  name: MESH-GRPC
  summary: Core tests partially succeeded with 1 test skips.
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 7
      Skipped: 0
  extended:
    result: success
    statistics:
      Failed: 0
      Passed: 5
      Skipped: 0
    supportedFeatures:
    - MeshClusterIPMatching
    - MeshConsumerRoute
    - MeshHTTPRouteBackendRequestHeaderModification
    - MeshHTTPRouteNamedRouteRule
    - MeshHTTPRouteQueryParamMatching
    - MeshHTTPRouteRedirectPort
    - MeshHTTPRouteSchemeRedirect
    unsupportedFeatures:
    - MeshHTTPRouteRedirectPath
    - MeshHTTPRouteRewritePath
  name: MESH-HTTP
  summary: Core tests succeeded. Extended tests succeeded.
succeededProvisionalTests:
- MeshHTTPRouteNamedRule
