/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha2 "sigs.k8s.io/gateway-api/apis/v1alpha2"
)

// FakeCustomGRPCRoutes implements CustomGRPCRouteInterface
type FakeCustomGRPCRoutes struct {
	Fake *FakeGatewayV1alpha2
	ns   string
}

var customgrpcroutesResource = schema.GroupVersionResource{Group: "gateway.networking.k8s.io", Version: "v1alpha2", Resource: "customgrpcroutes"}

var customgrpcroutesKind = schema.GroupVersionKind{Group: "gateway.networking.k8s.io", Version: "v1alpha2", Kind: "CustomGRPCRoute"}

// Get takes name of the customGRPCRoute, and returns the corresponding customGRPCRoute object, and an error if there is any.
func (c *FakeCustomGRPCRoutes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha2.CustomGRPCRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(customgrpcroutesResource, c.ns, name), &v1alpha2.CustomGRPCRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.CustomGRPCRoute), err
}

// List takes label and field selectors, and returns the list of CustomGRPCRoutes that match those selectors.
func (c *FakeCustomGRPCRoutes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha2.CustomGRPCRouteList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(customgrpcroutesResource, customgrpcroutesKind, c.ns, opts), &v1alpha2.CustomGRPCRouteList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha2.CustomGRPCRouteList{ListMeta: obj.(*v1alpha2.CustomGRPCRouteList).ListMeta}
	for _, item := range obj.(*v1alpha2.CustomGRPCRouteList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested customGRPCRoutes.
func (c *FakeCustomGRPCRoutes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(customgrpcroutesResource, c.ns, opts))

}

// Create takes the representation of a customGRPCRoute and creates it.  Returns the server's representation of the customGRPCRoute, and an error, if there is any.
func (c *FakeCustomGRPCRoutes) Create(ctx context.Context, customGRPCRoute *v1alpha2.CustomGRPCRoute, opts v1.CreateOptions) (result *v1alpha2.CustomGRPCRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(customgrpcroutesResource, c.ns, customGRPCRoute), &v1alpha2.CustomGRPCRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.CustomGRPCRoute), err
}

// Update takes the representation of a customGRPCRoute and updates it. Returns the server's representation of the customGRPCRoute, and an error, if there is any.
func (c *FakeCustomGRPCRoutes) Update(ctx context.Context, customGRPCRoute *v1alpha2.CustomGRPCRoute, opts v1.UpdateOptions) (result *v1alpha2.CustomGRPCRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(customgrpcroutesResource, c.ns, customGRPCRoute), &v1alpha2.CustomGRPCRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.CustomGRPCRoute), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCustomGRPCRoutes) UpdateStatus(ctx context.Context, customGRPCRoute *v1alpha2.CustomGRPCRoute, opts v1.UpdateOptions) (*v1alpha2.CustomGRPCRoute, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(customgrpcroutesResource, "status", c.ns, customGRPCRoute), &v1alpha2.CustomGRPCRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.CustomGRPCRoute), err
}

// Delete takes name of the customGRPCRoute and deletes it. Returns an error if one occurs.
func (c *FakeCustomGRPCRoutes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(customgrpcroutesResource, c.ns, name, opts), &v1alpha2.CustomGRPCRoute{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCustomGRPCRoutes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(customgrpcroutesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha2.CustomGRPCRouteList{})
	return err
}

// Patch applies the patch and returns the patched customGRPCRoute.
func (c *FakeCustomGRPCRoutes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.CustomGRPCRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(customgrpcroutesResource, c.ns, name, pt, data, subresources...), &v1alpha2.CustomGRPCRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.CustomGRPCRoute), err
}
