/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "sigs.k8s.io/service-apis/apis/v1alpha1"
)

// TcpRouteLister helps list TcpRoutes.
type TcpRouteLister interface {
	// List lists all TcpRoutes in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.TcpRoute, err error)
	// TcpRoutes returns an object that can list and get TcpRoutes.
	TcpRoutes(namespace string) TcpRouteNamespaceLister
	TcpRouteListerExpansion
}

// tcpRouteLister implements the TcpRouteLister interface.
type tcpRouteLister struct {
	indexer cache.Indexer
}

// NewTcpRouteLister returns a new TcpRouteLister.
func NewTcpRouteLister(indexer cache.Indexer) TcpRouteLister {
	return &tcpRouteLister{indexer: indexer}
}

// List lists all TcpRoutes in the indexer.
func (s *tcpRouteLister) List(selector labels.Selector) (ret []*v1alpha1.TcpRoute, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.TcpRoute))
	})
	return ret, err
}

// TcpRoutes returns an object that can list and get TcpRoutes.
func (s *tcpRouteLister) TcpRoutes(namespace string) TcpRouteNamespaceLister {
	return tcpRouteNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// TcpRouteNamespaceLister helps list and get TcpRoutes.
type TcpRouteNamespaceLister interface {
	// List lists all TcpRoutes in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.TcpRoute, err error)
	// Get retrieves the TcpRoute from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.TcpRoute, error)
	TcpRouteNamespaceListerExpansion
}

// tcpRouteNamespaceLister implements the TcpRouteNamespaceLister
// interface.
type tcpRouteNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all TcpRoutes in the indexer for a given namespace.
func (s tcpRouteNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.TcpRoute, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.TcpRoute))
	})
	return ret, err
}

// Get retrieves the TcpRoute from the indexer for a given namespace and name.
func (s tcpRouteNamespaceLister) Get(name string) (*v1alpha1.TcpRoute, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("tcproute"), name)
	}
	return obj.(*v1alpha1.TcpRoute), nil
}
