apiVersion: internal.gateway.networking.k8s.io/v1alpha2
kind: GEPDetails
number: 3171
name: Percentage-based Request Mirroring
status: Standard
authors:
  - jakebennert
  - LiorLieberman
references:
  - https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io%2fv1.HTTPRequestMirrorFilter
  - https://github.com/kubernetes-sigs/gateway-api/pull/3199
  - https://github.com/kubernetes-sigs/gateway-api/pull/3301
  - https://github.com/kubernetes-sigs/gateway-api/pull/3638
  - https://github.com/kubernetes-sigs/gateway-api/pull/3508
featureNames:
  - HTTPRouteRequestPercentageMirror
