apiVersion: gateway.networking.k8s.io/v1alpha1
date: "2024-06-12T19:26:43Z"
gatewayAPIVersion: v1.0.0
implementation:
  contact:
  - '@projectcontour/maintainers'
  organization: projectcontour
  project: contour
  url: https://projectcontour.io/
  version: v1.28.5
kind: ConformanceReport
profiles:
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 10
      Skipped: 0
    summary: ""
  name: TLS
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 29
      Skipped: 0
    summary: ""
  extended:
    result: partial
    skippedTests:
    - HTTPRouteTimeoutBackendRequest
    statistics:
      Failed: 0
      Passed: 11
      Skipped: 1
    summary: ""
    supportedFeatures:
    - HTTPRoutePathRewrite
    - HTTPRouteSchemeRedirect
    - HTTPRouteBackendTimeout
    - HTTPRouteQueryParamMatching
    - HTTPRouteMethodMatching
    - HTTPRouteRequestMirror
    - HTTPRouteHostRewrite
    - HTTPRoutePortRedirect
    - HTTPRouteResponseHeaderModification
    - HTTPRouteRequestMultipleMirrors
    - HTTPRouteRequestTimeout
    - HTTPRoutePathRedirect
  name: HTTP
