apiVersion: gateway.networking.k8s.io/v1alpha1
date: "2024-05-07T19:37:29Z"
gatewayAPIVersion: v1.0.0
implementation:
  contact:
  - '@projectcontour/maintainers'
  organization: projectcontour
  project: contour
  url: https://projectcontour.io/
  version: v1.28.4
kind: ConformanceReport
profiles:
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 29
      Skipped: 0
    summary: ""
  extended:
    result: partial
    skippedTests:
    - HTTPRouteTimeoutBackendRequest
    statistics:
      Failed: 0
      Passed: 11
      Skipped: 1
    summary: ""
    supportedFeatures:
    - HTTPRouteSchemeRedirect
    - HTTPRouteRequestTimeout
    - HTTPRoutePortRedirect
    - HTTPRouteRequestMultipleMirrors
    - HTTPRouteQueryParamMatching
    - HTTPRouteMethodMatching
    - HTTPRouteResponseHeaderModification
    - HTTPRoutePathRedirect
    - HTTPRoutePathRewrite
    - HTTPRouteBackendTimeout
    - HTTPRouteHostRewrite
    - HTTPRouteRequestMirror
  name: HTTP
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 10
      Skipped: 0
    summary: ""
  name: TLS
