apiVersion: internal.gateway.networking.k8s.io/v1alpha1
kind: GEPDetails
number: 1767
name: CORS Filter
status: Standard
authors:
  - lianglli
  - robscott
  - EyalPazz
  - shaneutt
  - DamianSawicki
references:
  - https://github.com/kubernetes-sigs/gateway-api/pull/3435
  - https://github.com/kubernetes-sigs/gateway-api/pull/3637
  - https://github.com/kubernetes-sigs/gateway-api/pull/3656
  - https://github.com/kubernetes-sigs/gateway-api/pull/3668
  - https://github.com/kubernetes-sigs/gateway-api/pull/4281
  - https://github.com/kubernetes-sigs/gateway-api/pull/4506
  - https://github.com/kubernetes-sigs/gateway-api/pull/4579

