apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GRPCRoute
metadata:
  name: invalid-filter-duplicate-header
spec:
  rules:
  - filters:
    - type: RequestHeaderModifier
      requestHeaderModifier:
        remove:
        - foo
        - foo
