/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// reportfeatures verifies that the conformance reports only list features that
// exist in the Gateway API release they were submitted for. This prevents
// reports generated from the main branch from being filed as release reports.
//
// The features of the release under development are defined by pkg/features.
// When a release is cut, they are recorded in a snapshot
// (conformance/release-features/vX.Y.yaml) using the -generate flag, so that
// reports for that release can still be verified once main has moved on.
package main

import (
	"flag"
	"fmt"
	"io/fs"
	"log"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"golang.org/x/mod/semver"
	"sigs.k8s.io/yaml"

	v1 "sigs.k8s.io/gateway-api/conformance/apis/v1"
	"sigs.k8s.io/gateway-api/pkg/features"
)

const snapshotHeader = `# This file lists the features available in Gateway API %[1]s.
# It is generated by "go run ./tools/reportfeatures -generate %[1]s" when a
# release is cut, and is used to verify conformance reports. Do not edit it by hand.
`

type config struct {
	// ReportsDir is the directory containing the conformance reports.
	ReportsDir string
	// SnapshotsDir is the directory containing the per-release feature snapshots.
	SnapshotsDir string
	// Generate is the release (vMAJOR.MINOR) to write a snapshot for.
	Generate string
	// Prune removes invalid features from the reports instead of failing.
	Prune bool
}

func main() {
	var cfg config
	flag.StringVar(&cfg.ReportsDir, "r", "conformance/reports", "Defines the path relative to the repo root of the directory containing the conformance reports")
	flag.StringVar(&cfg.SnapshotsDir, "s", "conformance/release-features", "Defines the path relative to the repo root of the directory containing the per-release feature snapshots")
	flag.StringVar(&cfg.Generate, "generate", "", "Writes a snapshot of the features currently defined in pkg/features for the given release (vMAJOR.MINOR, e.g. v1.6) and exits. Run it when cutting a release")
	flag.BoolVar(&cfg.Prune, "prune", false, "Removes the features that do not exist in a report's release from the report, instead of failing")
	flag.Parse()

	log.SetOutput(os.Stdout)

	if cfg.Generate != "" {
		if err := generateSnapshot(cfg.SnapshotsDir, cfg.Generate); err != nil {
			log.Fatalf("Couldn't generate the feature snapshot: %s", err)
		}
		return
	}

	problems, err := verifyReports(cfg)
	if err != nil {
		log.Fatalf("Couldn't verify the conformance reports: %s", err)
	}
	if len(problems) > 0 {
		for _, problem := range problems {
			log.Print(problem)
		}
		log.Fatalf("%d conformance report(s) list features that do not exist in their release, "+
			"run \"go run ./tools/reportfeatures -prune\" to remove them", len(problems))
	}
}

// releaseVersion returns v if it is a valid vMAJOR.MINOR release.
func releaseVersion(v string) (string, error) {
	if v == "" || semver.MajorMinor(v) != v {
		return "", fmt.Errorf("%q is not a valid release, expected vMAJOR.MINOR (e.g. v1.6)", v)
	}
	return v, nil
}

// currentFeatures returns the features currently defined in pkg/features.
func currentFeatures() (ReleaseFeatures, error) {
	var rf ReleaseFeatures
	for _, feature := range features.AllFeatures.UnsortedList() {
		switch feature.Channel {
		case features.FeatureChannelStandard:
			rf.Standard = append(rf.Standard, string(feature.Name))
		case features.FeatureChannelExperimental:
			rf.Experimental = append(rf.Experimental, string(feature.Name))
		default:
			return rf, fmt.Errorf("feature %q has an unknown channel %q", feature.Name, feature.Channel)
		}
	}
	rf.Standard = sortedUnique(rf.Standard)
	rf.Experimental = sortedUnique(rf.Experimental)
	return rf, nil
}

// generateSnapshot writes the features currently defined in pkg/features to the
// snapshot of the given release.
func generateSnapshot(dir, release string) error {
	release, err := releaseVersion(release)
	if err != nil {
		return err
	}

	rf, err := currentFeatures()
	if err != nil {
		return err
	}
	body, err := yaml.Marshal(rf)
	if err != nil {
		return err
	}
	content := append(fmt.Appendf(nil, snapshotHeader, release), body...)

	if err = os.MkdirAll(dir, 0o750); err != nil {
		return err
	}
	path := filepath.Join(dir, release+".yaml")
	if err = os.WriteFile(path, content, 0o600); err != nil {
		return err
	}
	log.Printf("Wrote %d standard and %d experimental features to %s", len(rf.Standard), len(rf.Experimental), path)
	return nil
}

// loadSnapshots reads the per-release snapshots, keyed by release (vMAJOR.MINOR).
func loadSnapshots(dir string) (map[string]ReleaseFeatures, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}

	snapshots := make(map[string]ReleaseFeatures)
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".yaml" {
			continue
		}
		release, nameErr := releaseVersion(strings.TrimSuffix(entry.Name(), ".yaml"))
		if nameErr != nil {
			return nil, fmt.Errorf("unexpected snapshot file %s: %w", entry.Name(), nameErr)
		}
		content, readErr := os.ReadFile(filepath.Join(dir, entry.Name()))
		if readErr != nil {
			return nil, readErr
		}
		var rf ReleaseFeatures
		if parseErr := yaml.Unmarshal(content, &rf); parseErr != nil {
			return nil, fmt.Errorf("parsing %s: %w", entry.Name(), parseErr)
		}
		snapshots[release] = rf
	}
	return snapshots, nil
}

// validFeatures returns the names of the features that exist in the given
// release. The boolean is false when the release cannot be verified because it
// is older than the oldest snapshot.
//
//   - A release with a snapshot is verified against its snapshot.
//   - A release newer than every snapshot is the one under development or one
//     that was just released, so the features currently defined in
//     pkg/features are used.
//   - A release with no snapshot between two snapshots is an error, as its
//     snapshot is missing.
func validFeatures(release string, snapshots map[string]ReleaseFeatures) (map[string]struct{}, bool, error) {
	if rf, ok := snapshots[release]; ok {
		return rf.Names(), true, nil
	}

	releases := make([]string, 0, len(snapshots))
	for r := range snapshots {
		releases = append(releases, r)
	}
	if len(releases) == 0 {
		return nil, false, fmt.Errorf("there are no feature snapshots to verify %s against", release)
	}
	semver.Sort(releases)

	switch {
	case semver.Compare(release, releases[0]) < 0:
		return nil, false, nil
	case semver.Compare(release, releases[len(releases)-1]) > 0:
		rf, err := currentFeatures()
		if err != nil {
			return nil, false, err
		}
		return rf.Names(), true, nil
	default:
		return nil, false, fmt.Errorf("there is no feature snapshot for %[1]s, generate it with \"go run ./tools/reportfeatures -generate %[1]s\" on the %[1]s release", release)
	}
}

// reportFeatureNames returns the names of all the features listed in a report,
// whether they are supported or not.
func reportFeatureNames(report *v1.ConformanceReport) []string {
	var names []string
	for _, profile := range report.ProfileReports {
		if profile.Extended == nil {
			continue
		}
		names = append(names, profile.Extended.SupportedFeatures...)
		names = append(names, profile.Extended.UnsupportedFeatures...)
	}
	return names
}

// verifyReports checks that every report only lists features that exist in its
// release. It returns a message for each report that does not. With
// cfg.Prune the invalid features are removed from the reports instead.
func verifyReports(cfg config) ([]string, error) {
	snapshots, err := loadSnapshots(cfg.SnapshotsDir)
	if err != nil {
		return nil, err
	}

	type releaseFeatures struct {
		names      map[string]struct{}
		verifiable bool
	}
	releases := make(map[string]releaseFeatures)

	var problems []string
	// WalkDir does not follow symbolic links, so the release directories that
	// are links to another one (e.g. v1.6.0 -> v1.6) are only verified once.
	err = filepath.WalkDir(cfg.ReportsDir, func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return fmt.Errorf("error accessing %s: %w", path, walkErr)
		}
		if d.IsDir() || filepath.Ext(d.Name()) != ".yaml" {
			return nil
		}

		relPath, relErr := filepath.Rel(cfg.ReportsDir, path)
		if relErr != nil {
			return relErr
		}
		dirName, _, _ := strings.Cut(filepath.ToSlash(relPath), "/")
		release := semver.MajorMinor(dirName)
		if release == "" {
			return nil
		}

		valid, seen := releases[release]
		if !seen {
			names, verifiable, featErr := validFeatures(release, snapshots)
			if featErr != nil {
				return featErr
			}
			if !verifiable {
				log.Printf("Skipping the reports of %s, which is older than the oldest feature snapshot", release)
			}
			valid = releaseFeatures{names: names, verifiable: verifiable}
			releases[release] = valid
		}
		if !valid.verifiable {
			return nil
		}

		problem, checkErr := checkReport(cfg, path, relPath, release, valid.names)
		if checkErr != nil {
			return checkErr
		}
		if problem != "" {
			problems = append(problems, problem)
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	return problems, nil
}

// checkReport verifies a single report against the features of its release, or
// prunes it when cfg.Prune is set. It returns a message if the report lists
// features that do not exist in the release and was not pruned.
func checkReport(cfg config, path, relPath, release string, valid map[string]struct{}) (string, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	report := &v1.ConformanceReport{}
	if err = yaml.Unmarshal(content, report); err != nil {
		return "", fmt.Errorf("parsing %s: %w", relPath, err)
	}

	invalid := invalidNames(reportFeatureNames(report), valid)
	if len(invalid) == 0 {
		return "", nil
	}

	if !cfg.Prune {
		return fmt.Sprintf("%s lists features that do not exist in Gateway API %s: %s",
			relPath, release, strings.Join(invalid, ", ")), nil
	}

	invalidSet := make(map[string]struct{}, len(invalid))
	for _, name := range invalid {
		invalidSet[name] = struct{}{}
	}
	pruned, removed := pruneFeatures(content, invalidSet)
	if !slices.Equal(removed, invalid) {
		return "", fmt.Errorf("couldn't prune %s: removed %v but %v are invalid, the file layout is not the expected one",
			relPath, removed, invalid)
	}
	info, err := os.Stat(path)
	if err != nil {
		return "", err
	}
	if err = os.WriteFile(path, pruned, info.Mode().Perm()); err != nil {
		return "", err
	}
	log.Printf("Pruned %s from %s", strings.Join(removed, ", "), relPath)
	return "", nil
}
