resources:
  - 0-namespace.yaml
  - certificate_config.yaml
  - admission_webhook.yaml
patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: registry.k8s.io/gateway-api/admission-server:latest
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
    target:
      group: apps
      version: v1
      kind: Deployment
      name: gateway-api-admission-server
