apiVersion: gateway.networking.k8s.io/v1alpha1
date: "2024-07-31T19:28:39Z"
gatewayAPIChannel: experimental
gatewayAPIVersion: v1.1.0
implementation:
  contact:
  - https://github.com/envoyproxy/gateway/blob/main/GOVERNANCE.md
  organization: envoyproxy
  project: envoy-gateway
  url: https://github.com/envoyproxy/gateway
  version: v1.1.0
kind: ConformanceReport
mode: default
profiles:
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 12
      Skipped: 0
  extended:
    result: partial
    skippedTests:
    - GatewayStaticAddresses
    statistics:
      Failed: 0
      Passed: 0
      Skipped: 1
    supportedFeatures:
    - GatewayHTTPListenerIsolation
    - GatewayPort8080
    - GatewayStaticAddresses
  name: GATEWAY-GRPC
  summary: Core tests succeeded. Extended tests partially succeeded with 1 test skips.
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 33
      Skipped: 0
  extended:
    result: partial
    skippedTests:
    - GatewayHTTPListenerIsolation
    - GatewayStaticAddresses
    statistics:
      Failed: 0
      Passed: 17
      Skipped: 2
    supportedFeatures:
    - GatewayHTTPListenerIsolation
    - GatewayPort8080
    - GatewayStaticAddresses
    - HTTPRouteBackendRequestHeaderModification
    - HTTPRouteBackendTimeout
    - HTTPRouteHostRewrite
    - HTTPRouteMethodMatching
    - HTTPRouteParentRefPort
    - HTTPRoutePathRedirect
    - HTTPRoutePathRewrite
    - HTTPRoutePortRedirect
    - HTTPRouteQueryParamMatching
    - HTTPRouteRequestMirror
    - HTTPRouteRequestMultipleMirrors
    - HTTPRouteRequestTimeout
    - HTTPRouteResponseHeaderModification
    - HTTPRouteSchemeRedirect
  name: GATEWAY-HTTP
  summary: Core tests succeeded. Extended tests partially succeeded with 2 test skips.
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 11
      Skipped: 0
  extended:
    result: partial
    skippedTests:
    - GatewayStaticAddresses
    statistics:
      Failed: 0
      Passed: 0
      Skipped: 1
    supportedFeatures:
    - GatewayHTTPListenerIsolation
    - GatewayPort8080
    - GatewayStaticAddresses
  name: GATEWAY-TLS
  summary: Core tests succeeded. Extended tests partially succeeded with 1 test skips.
