# These namespaces can be used for examples without recreating them each time.
---
kind: Namespace
apiVersion: v1
metadata:
  name: gateway-api-example-ns1
---
kind: Namespace
apiVersion: v1
metadata:
  name: gateway-api-example-ns2
