kind: GatewayClass
apiVersion: gateway.networking.k8s.io/v1alpha2
metadata:
  name: default-match-example
spec:
  controller: acme.io/gateway-controller
---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1alpha2
metadata:
  name: default-match-gw
spec:
  gatewayClassName: default-match-example
  listeners:
  - protocol: HTTP
    port: 80
    routes:
      kind: HTTPRoute
      selector:
        matchLabels:
          app: default-match
      namespaces:
        from: "All"
---
# This HTTPRoute demonstrates patch match defaulting. If no path match is
# specified, CRD defaults adds a default prefix match on the path "/". This
# matches every HTTP request and ensures that route rules always have at
# least one valid match.
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1alpha2
metadata:
  name: default-match-route
  labels:
    app: default-match
spec:
  hostnames:
    - default-match.com
  rules:
  - matches:
    - headers:
      - type: Exact
        name: magic
        value: default-match
    backendRefs:
    - group: acme.io
      kind: CustomBackend
      name: my-custom-resource
      port: 8080
  - matches:
    - path:
        type: Exact
        value: /example/exact
    backendRefs:
    - name: my-service-2
      port: 8080
