kind: GatewayClass
apiVersion: networking.x-k8s.io/v1alpha2
metadata:
  name: filter-lb
spec: 
  controller: acme.io/gateway-controller
  parametersRef:
    name: acme-lb
    group: acme.io
    kind: Parameters
---
kind: Namespace
apiVersion: v1
metadata:
  name: gateway-api-example-ns1
---
kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha2
metadata:
  name: my-filter-gateway
  namespace: gateway-api-example-ns1
spec:
  gatewayClassName: filter-lb
  listeners:
    - protocol: HTTP
      port: 80
      routes:
        kind: HTTPRoute
        selector:
          matchLabels:
            protocol: http
        namespaces:
          from: "Same"
    - protocol: HTTPS
      port: 443
      routes:
        kind: HTTPRoute
        selector:
          matchLabels:
            app: filter
        namespaces:
          from: "All"
---
kind: HTTPRoute
apiVersion: networking.x-k8s.io/v1alpha2
metadata:
  name: http-filter-1
  namespace: gateway-api-example-ns1
  labels:
    protocol: http
spec:
  hostnames:
    - my-filter.example.com
  rules:
    - matches:
      - path:
          type: Prefix
          value: /
      filters:
      - type: RequestRedirect
        requestRedirect:
          protocol: HTTPS
---
kind: HTTPRoute
apiVersion: networking.x-k8s.io/v1alpha2
metadata:
  name: http-filter-1
  labels:
    app: filter
spec:
  hostnames:
    - my-filter.example.com
  rules:
    - matches:
      - path:
          type: Prefix
          value: /
      forwardTo:
      - serviceName: my-filter-svc1
        weight: 1
        port: 80
