kind: HTTPRoute
apiVersion: networking.x-k8s.io/v1alpha2
metadata:
  name: foo-route
  labels:
    gateway: prod-web-gw
spec:
  hostnames:
  - foo.example.com
  rules:
  - forwardTo:
    - serviceName: foo-v1
      port: 8080
  - matches:
    - headers:
      - type: Exact
        name: traffic
        value: test
    forwardTo:
    - serviceName: foo-v2
      port: 8080
