apiVersion: gateway.networking.k8s.io/v1
date: "2026-06-09T09:10:31Z"
gatewayAPIChannel: experimental
gatewayAPIVersion: v1.5.1
implementation:
  contact:
  - https://github.com/kong/kong-operator/issues/new/choose
  organization: Kong
  project: kong-operator
  url: https://github.com/kong/kong-operator
  version: v2.2.0
kind: ConformanceReport
mode: traditional_compatible
profiles:
- core:
    result: partial
    skippedTests:
    - HTTPRouteHeaderMatching
    - HTTPRouteInvalidBackendRefUnknownKind
    statistics:
      Failed: 0
      Passed: 31
      Skipped: 2
  extended:
    result: success
    statistics:
      Failed: 0
      Passed: 5
      Skipped: 0
    supportedFeatures:
    - GatewayInfrastructurePropagation
    - GatewayPort8080
    - HTTPRouteHostRewrite
    - HTTPRoutePathRewrite
    - HTTPRouteResponseHeaderModification
    unsupportedFeatures:
    - BackendTLSPolicy
    - BackendTLSPolicySANValidation
    - GatewayAddressEmpty
    - GatewayBackendClientCertificate
    - GatewayFrontendClientCertificateValidation
    - GatewayFrontendClientCertificateValidationInsecureFallback
    - GatewayHTTPListenerIsolation
    - GatewayHTTPSListenerDetectMisdirectedRequests
    - GatewayStaticAddresses
    - HTTPRoute303RedirectStatusCode
    - HTTPRoute307RedirectStatusCode
    - HTTPRoute308RedirectStatusCode
    - HTTPRouteBackendProtocolH2C
    - HTTPRouteBackendProtocolWebSocket
    - HTTPRouteBackendRequestHeaderModification
    - HTTPRouteBackendTimeout
    - HTTPRouteCORS
    - HTTPRouteDestinationPortMatching
    - HTTPRouteMethodMatching
    - HTTPRouteNamedRouteRule
    - HTTPRouteParentRefPort
    - HTTPRoutePathRedirect
    - HTTPRoutePortRedirect
    - HTTPRouteQueryParamMatching
    - HTTPRouteRequestMirror
    - HTTPRouteRequestMultipleMirrors
    - HTTPRouteRequestPercentageMirror
    - HTTPRouteRequestTimeout
    - HTTPRouteSchemeRedirect
    - ListenerSet
  name: GATEWAY-HTTP
  summary: Core tests partially succeeded with 2 test skips. Extended tests succeeded.
- core:
    result: partial
    skippedTests:
    - GRPCExactMethodMatching
    - GRPCRouteHeaderMatching
    - GRPCRouteListenerHostnameMatching
    - GRPCRouteWeight
    statistics:
      Failed: 0
      Passed: 9
      Skipped: 4
  extended:
    result: success
    statistics:
      Failed: 0
      Passed: 1
      Skipped: 0
    supportedFeatures:
    - GatewayInfrastructurePropagation
    - GatewayPort8080
    unsupportedFeatures:
    - GatewayAddressEmpty
    - GatewayBackendClientCertificate
    - GatewayFrontendClientCertificateValidation
    - GatewayFrontendClientCertificateValidationInsecureFallback
    - GatewayHTTPListenerIsolation
    - GatewayHTTPSListenerDetectMisdirectedRequests
    - GatewayStaticAddresses
    - ListenerSet
  name: GATEWAY-GRPC
  summary: Core tests partially succeeded with 4 test skips. Extended tests succeeded.
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 18
      Skipped: 0
  extended:
    result: success
    statistics:
      Failed: 0
      Passed: 4
      Skipped: 0
    supportedFeatures:
    - GatewayInfrastructurePropagation
    - GatewayPort8080
    - TLSRouteModeTerminate
    unsupportedFeatures:
    - GatewayAddressEmpty
    - GatewayBackendClientCertificate
    - GatewayFrontendClientCertificateValidation
    - GatewayFrontendClientCertificateValidationInsecureFallback
    - GatewayHTTPListenerIsolation
    - GatewayHTTPSListenerDetectMisdirectedRequests
    - GatewayStaticAddresses
    - ListenerSet
    - TLSRouteModeMixed
  name: GATEWAY-TLS
  summary: Core tests succeeded. Extended tests succeeded.
succeededProvisionalTests:
- GatewayInfrastructure
- TLSRouteTerminateSimpleSameNamespace
