apiVersion: internal.gateway.networking.k8s.io/v1alpha1
kind: GEPDetails
number: 2257
name: Gateway API Duration Format
status: Standard
authors:
  - kflynn
relationships:
  seeAlso:
    - number: 1742
      name: HTTPRoute Timeouts
      description: HTTPRoute Timeouts use the format specified in this GEP.
references:
  - https://datatracker.ietf.org/doc/html/rfc8174
  - https://datatracker.ietf.org/doc/html/rfc2119
  - https://github.com/kubernetes-sigs/gateway-api/pull/2155
changelog:
  - https://github.com/kubernetes-sigs/gateway-api/pull/3210
