apiVersion: gateway.networking.kubernetes.io/v1
kind: ImplementationListDetails
organization: GKE
project: gke-gateway
fullName: Google Kubernetes Engine
description: |
  [Google Kubernetes Engine (GKE)][gke] is a managed Kubernetes platform offered
  by Google Cloud. GKE's implementation of the Gateway API is through the [GKE
  Gateway controller][gke-gateway] which provisions Google Cloud Load Balancers
  for Pods in GKE clusters.

  The GKE Gateway controller supports weighted traffic splitting, mirroring,
  advanced routing, multi-cluster load balancing and more. See the docs to deploy
  [private or public Gateways][gke-gateway-deploy] and also [multi-cluster
  Gateways][gke-multi-cluster-gateway].

  [gke]:https://cloud.google.com/kubernetes-engine
  [gke-gateway]:https://cloud.google.com/kubernetes-engine/docs/concepts/gateway-api
  [gke-gateway-deploy]:https://cloud.google.com/kubernetes-engine/docs/how-to/deploying-gateways
  [gke-multi-cluster-gateway]:https://cloud.google.com/kubernetes-engine/docs/how-to/deploying-multi-cluster-gateways
