kind: TCPRoute/CustomRoute
metadata:
  name: service-route
spec:
  parentRefs:
  - name: example-cluster-ip-gateway
  rules:
    config:
	sessionAffinity: false
    backendRefs:
    - kind: EndpointSelector
port: 8080
name: exampleapp-app-pods
---
apiVersion: gateway.networking.k8s.io/v1alpha1
kind: EndpointSelector
metadata:
  name: exampleapp-app-pods
spec:
  selector:
  - key: app
    value: exampleapp
    operator: In  


