apiVersion: gateway.networking.k8s.io/v1
date: "2026-01-16T14:43:48-08:00"
gatewayAPIChannel: experimental
gatewayAPIVersion: v1.4.1
implementation:
  contact:
  - github.com/kgateway-dev/kgateway/issues/new/choose
  organization: kgateway-dev
  project: kgateway
  url: github.com/kgateway-dev/kgateway
  version: v2.2.0-beta.6
kind: ConformanceReport
mode: default
profiles:
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 33
      Skipped: 0
  name: GATEWAY-HTTP
  summary: Core tests succeeded.
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 13
      Skipped: 0
  name: GATEWAY-GRPC
  summary: Core tests succeeded.
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 11
      Skipped: 0
  name: GATEWAY-TLS
  summary: Core tests succeeded.
