apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: portless-service
spec:
  parentRefs:
  - name: prod-web
  rules:
  - backendRefs:
    - name: foo
      kind: Service
      group: ""
