apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: invalid-backend-port
spec:
  rules:
  - backendRefs:
    - name: my-service
      port: 8080
    filters:
    - type: RequestRedirect
      requestRedirect:
        hostname: "*.gateway.networking.k8s.io"

