apiVersion: gateway.networking.k8s.io/v1
date: "2024-10-04T00:00:38Z"
gatewayAPIChannel: experimental
gatewayAPIVersion: v1.2.0
implementation:
  contact:
    - https://github.com/cilium/community/blob/main/roles/Maintainers.md
  organization: cilium
  project: cilium
  url: github.com/cilium/cilium
  version: v1.17.0-pre.1
kind: ConformanceReport
mode: default
profiles:
  - core:
      result: success
      statistics:
        Failed: 0
        Passed: 12
        Skipped: 0
    extended:
      result: success
      statistics:
        Failed: 0
        Passed: 2
        Skipped: 0
      supportedFeatures:
        - GatewayHTTPListenerIsolation
        - GatewayInfrastructurePropagation
        - GatewayPort8080
        - GatewayStaticAddresses
    name: GATEWAY-GRPC
    summary: Core tests succeeded. Extended tests succeeded.
  - core:
      result: success
      statistics:
        Failed: 0
        Passed: 33
        Skipped: 0
    extended:
      result: success
      statistics:
        Failed: 0
        Passed: 21
        Skipped: 0
      supportedFeatures:
        - GatewayHTTPListenerIsolation
        - GatewayInfrastructurePropagation
        - GatewayPort8080
        - GatewayStaticAddresses
        - HTTPRouteBackendProtocolH2C
        - HTTPRouteBackendProtocolWebSocket
        - HTTPRouteBackendRequestHeaderModification
        - HTTPRouteBackendTimeout
        - HTTPRouteDestinationPortMatching
        - HTTPRouteHostRewrite
        - HTTPRouteMethodMatching
        - HTTPRoutePathRedirect
        - HTTPRoutePathRewrite
        - HTTPRoutePortRedirect
        - HTTPRouteQueryParamMatching
        - HTTPRouteRequestMirror
        - HTTPRouteRequestMultipleMirrors
        - HTTPRouteRequestTimeout
        - HTTPRouteResponseHeaderModification
        - HTTPRouteSchemeRedirect
      unsupportedFeatures:
        - HTTPRouteParentRefPort
    name: GATEWAY-HTTP
    summary: Core tests succeeded. Extended tests succeeded.
  - core:
      result: success
      statistics:
        Failed: 0
        Passed: 11
        Skipped: 0
    extended:
      result: success
      statistics:
        Failed: 0
        Passed: 2
        Skipped: 0
      supportedFeatures:
        - GatewayHTTPListenerIsolation
        - GatewayInfrastructurePropagation
        - GatewayPort8080
        - GatewayStaticAddresses
    name: GATEWAY-TLS
    summary: Core tests succeeded. Extended tests succeeded.
  - core:
      result: success
      statistics:
        Failed: 0
        Passed: 1
        Skipped: 0
    name: MESH-GRPC
    summary: Core tests succeeded.
  - core:
      result: success
      statistics:
        Failed: 0
        Passed: 2
        Skipped: 0
    extended:
      result: success
      statistics:
        Failed: 0
        Passed: 2
        Skipped: 0
      supportedFeatures:
        - HTTPRouteBackendProtocolH2C
        - HTTPRouteBackendProtocolWebSocket
        - HTTPRouteBackendRequestHeaderModification
        - HTTPRouteBackendTimeout
        - HTTPRouteDestinationPortMatching
        - HTTPRouteHostRewrite
        - HTTPRouteMethodMatching
        - HTTPRoutePathRedirect
        - HTTPRoutePathRewrite
        - HTTPRoutePortRedirect
        - HTTPRouteQueryParamMatching
        - HTTPRouteRequestMirror
        - HTTPRouteRequestMultipleMirrors
        - HTTPRouteRequestTimeout
        - HTTPRouteResponseHeaderModification
        - HTTPRouteSchemeRedirect
        - MeshClusterIPMatching
      unsupportedFeatures:
        - HTTPRouteParentRefPort
        - MeshConsumerRoute
    name: MESH-HTTP
    summary: Core tests succeeded. Extended tests succeeded.
succeededProvisionalTests:
  - GatewayInfrastructure
