/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "sigs.k8s.io/gateway-api/apis/v1"
	apisxv1alpha1 "sigs.k8s.io/gateway-api/apisx/v1alpha1"
)

// AttributeApplyConfiguration represents a declarative configuration of the Attribute type for use
// with apply.
//
// Attribute defines a single flat key-value pair to attach to traces.
//
// This allows users to enrich spans with context like HTTP headers
// (e.g., "X-User-ID"), static tags, or built-in variables.
//
// Support: Core
type AttributeApplyConfiguration struct {
	// Name is the key of the attribute as it will appear in the output
	// (i.e., as a span tag).
	//
	Name *apisxv1alpha1.AttributeName `json:"name,omitempty"`
	// SourceType specifies where the attribute value comes from.
	// Valid values are "Header", "Literal", or "Attribute".
	//
	SourceType *apisxv1alpha1.AttributeSourceType `json:"sourceType,omitempty"`
	// HeaderName specifies the HTTP header to extract the value from.
	// This is required if SourceType is "Header".
	//
	HeaderName *v1.HTTPHeaderName `json:"headerName,omitempty"`
	// LiteralValue specifies a static string value to attach.
	// This is required if SourceType is "Literal".
	//
	LiteralValue *string `json:"literalValue,omitempty"`
	// AttributeKey refers to a standard OpenTelemetry attribute.
	// For example: "http.response.status_code" or "http.request.method".
	// This is required if SourceType is "Attribute".
	// See: https://opentelemetry.io/docs/specs/semconv/
	//
	AttributeKey *string `json:"attributeKey,omitempty"`
}

// AttributeApplyConfiguration constructs a declarative configuration of the Attribute type for use with
// apply.
func Attribute() *AttributeApplyConfiguration {
	return &AttributeApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *AttributeApplyConfiguration) WithName(value apisxv1alpha1.AttributeName) *AttributeApplyConfiguration {
	b.Name = &value
	return b
}

// WithSourceType sets the SourceType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SourceType field is set to the value of the last call.
func (b *AttributeApplyConfiguration) WithSourceType(value apisxv1alpha1.AttributeSourceType) *AttributeApplyConfiguration {
	b.SourceType = &value
	return b
}

// WithHeaderName sets the HeaderName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HeaderName field is set to the value of the last call.
func (b *AttributeApplyConfiguration) WithHeaderName(value v1.HTTPHeaderName) *AttributeApplyConfiguration {
	b.HeaderName = &value
	return b
}

// WithLiteralValue sets the LiteralValue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LiteralValue field is set to the value of the last call.
func (b *AttributeApplyConfiguration) WithLiteralValue(value string) *AttributeApplyConfiguration {
	b.LiteralValue = &value
	return b
}

// WithAttributeKey sets the AttributeKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AttributeKey field is set to the value of the last call.
func (b *AttributeApplyConfiguration) WithAttributeKey(value string) *AttributeApplyConfiguration {
	b.AttributeKey = &value
	return b
}
