/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apisxv1alpha1 "sigs.k8s.io/gateway-api/apisx/v1alpha1"
)

// BackendPortApplyConfiguration represents a declarative configuration of the BackendPort type for use
// with apply.
//
// BackendPort describes the port the implementation should use when connecting
// to a Backend. Inspired by discoveryv1.EndpointPort.
type BackendPortApplyConfiguration struct {
	// Name represents the name of this port. All ports in a Backend must have
	// a unique name. Name must either be an empty string or pass DNS_LABEL
	// validation (lowercase alphanumeric or '-', starting and ending with an
	// alphanumeric character, at most 63 characters).
	Name *string `json:"name,omitempty"`
	// Port represents the port number of the endpoint.
	Port *apisxv1alpha1.PortNumber `json:"port,omitempty"`
}

// BackendPortApplyConfiguration constructs a declarative configuration of the BackendPort type for use with
// apply.
func BackendPort() *BackendPortApplyConfiguration {
	return &BackendPortApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *BackendPortApplyConfiguration) WithName(value string) *BackendPortApplyConfiguration {
	b.Name = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *BackendPortApplyConfiguration) WithPort(value apisxv1alpha1.PortNumber) *BackendPortApplyConfiguration {
	b.Port = &value
	return b
}
