/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// BackendStatusApplyConfiguration represents a declarative configuration of the BackendStatus type for use
// with apply.
//
// BackendStatus defines the observed state of a Backend.
type BackendStatusApplyConfiguration struct {
	// Ancestors is a list of parent resources associated with this Backend,
	// and the status of the Backend with respect to each parent.
	//
	// A maximum of 32 parents will be represented in this list. An empty list
	// indicates that the Backend is not associated with any parents.
	//
	// <gateway:util:excludeFromCRD>
	// Notes for implementers:
	//
	// A controller that manages the Backend must add an entry for each parent
	// it manages and remove the entry when the controller no longer considers
	// the Backend to be associated with that parent.
	//
	// TODO: We may discover that this creates unnecessary apiserver/informer overhead
	// for little benefit. It may also be unnecessarily complex for implementations to manage.
	// If so, we'll remove the ancestor-based grouping and make it controller only.
	// </gateway:util:excludeFromCRD>
	Ancestors []BackendAncestorStatusApplyConfiguration `json:"parents,omitempty"`
}

// BackendStatusApplyConfiguration constructs a declarative configuration of the BackendStatus type for use with
// apply.
func BackendStatus() *BackendStatusApplyConfiguration {
	return &BackendStatusApplyConfiguration{}
}

// WithAncestors adds the given value to the Ancestors field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Ancestors field.
func (b *BackendStatusApplyConfiguration) WithAncestors(values ...*BackendAncestorStatusApplyConfiguration) *BackendStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAncestors")
		}
		b.Ancestors = append(b.Ancestors, *values[i])
	}
	return b
}
