/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// BackendStatusApplyConfiguration represents a declarative configuration of the BackendStatus type for use
// with apply.
//
// BackendStatus defines the observed state of a Backend.
type BackendStatusApplyConfiguration struct {
	// Parents is a list of parent resources associated with this Backend,
	// and the status of the Backend with respect to each parent.
	//
	// A controller that manages the Backend must add an entry for each parent
	// it manages and remove the entry when the controller no longer considers
	// the Backend to be associated with that parent.
	//
	// A maximum of 32 parents will be represented in this list. An empty list
	// indicates that the Backend is not associated with any parents.
	Parents []BackendParentStatusApplyConfiguration `json:"parents,omitempty"`
}

// BackendStatusApplyConfiguration constructs a declarative configuration of the BackendStatus type for use with
// apply.
func BackendStatus() *BackendStatusApplyConfiguration {
	return &BackendStatusApplyConfiguration{}
}

// WithParents adds the given value to the Parents field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Parents field.
func (b *BackendStatusApplyConfiguration) WithParents(values ...*BackendParentStatusApplyConfiguration) *BackendStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithParents")
		}
		b.Parents = append(b.Parents, *values[i])
	}
	return b
}
