/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "sigs.k8s.io/gateway-api/apis/v1"
)

// EndpointSelectorBackendApplyConfiguration represents a declarative configuration of the EndpointSelectorBackend type for use
// with apply.
//
// EndpointSelectorBackend specifies the configuration for a backend that
// selects a set of pods by label.
type EndpointSelectorBackendApplyConfiguration struct {
	// Selector defines the label selector used to identify the set of pods whose
	// IP addresses will make up the endpoints that this Backend should route
	// traffic to.
	//
	// If this field is set, the endpoints are resolved automatically and stay up
	// to date as pods matching the selector are added or removed; the user does
	// not create or manage any separate endpoint resource.
	//
	// <gateway:util:excludeFromCRD>
	// Notes for implementers:
	//
	// This is an embedded struct to avoid stuttering in the API
	// (i.e. `endpointSelector.selector`).
	//
	// Implementations MAY create a Service from the label selector for endpoint
	// resolution until the upstream EndpointSelector resource (KEP-6116) is
	// available. Implementations SHOULD set ownerReferences so the created
	// resource's lifecycle is tied to this Backend. This Service only exists to
	// produce EndpointSlices; Service-level behaviors (including but not limited
	// to internalTrafficPolicy, externalTrafficPolicy, sessionAffinity, and
	// trafficDistribution) play no role. The Service port (ClusterIP frontend)
	// is unused; the targetPort SHOULD be set to Backend.spec.port.
	// Implementations SHOULD create the Service as headless (clusterIP: None),
	// since no ClusterIP or kube-proxy load balancing is needed.
	// Implementations MUST name the Service with generateName rather than a
	// predictable name, so that a name like <backend-name>-backend.svc.cluster.local
	// does not become a relied-upon DNS entry.
	// </gateway:util:excludeFromCRD>
	LabelSelectorApplyConfiguration `json:""`
}

// EndpointSelectorBackendApplyConfiguration constructs a declarative configuration of the EndpointSelectorBackend type for use with
// apply.
func EndpointSelectorBackend() *EndpointSelectorBackendApplyConfiguration {
	return &EndpointSelectorBackendApplyConfiguration{}
}

// WithMatchLabels puts the entries into the MatchLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the MatchLabels field,
// overwriting an existing map entries in MatchLabels field with the same key.
func (b *EndpointSelectorBackendApplyConfiguration) WithMatchLabels(entries map[v1.LabelKey]v1.LabelValue) *EndpointSelectorBackendApplyConfiguration {
	if b.LabelSelectorApplyConfiguration.MatchLabels == nil && len(entries) > 0 {
		b.LabelSelectorApplyConfiguration.MatchLabels = make(map[v1.LabelKey]v1.LabelValue, len(entries))
	}
	for k, v := range entries {
		b.LabelSelectorApplyConfiguration.MatchLabels[k] = v
	}
	return b
}
