/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "sigs.k8s.io/gateway-api/apis/v1"
)

// ExternalHostnameBackendApplyConfiguration represents a declarative configuration of the ExternalHostnameBackend type for use
// with apply.
//
// ExternalHostnameBackend specifies the configuration for a backend that
// represents an external hostname destination.
type ExternalHostnameBackendApplyConfiguration struct {
	// Hostname specifies the FQDN used to reach this backend.
	// IP addresses are not allowed in this field.
	//
	// <gateway:util:excludeFromCRD>
	// Notes for implementers:
	//
	// Implementations that are aware of custom trust domains being used for
	// Service FQDNs MUST also enforce that hostnames ending with those trust
	// domains (e.g. .cluster.local) are not allowed.
	// </gateway:util:excludeFromCRD>
	Hostname *v1.PreciseHostname `json:"hostname,omitempty"`
}

// ExternalHostnameBackendApplyConfiguration constructs a declarative configuration of the ExternalHostnameBackend type for use with
// apply.
func ExternalHostnameBackend() *ExternalHostnameBackendApplyConfiguration {
	return &ExternalHostnameBackendApplyConfiguration{}
}

// WithHostname sets the Hostname field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Hostname field is set to the value of the last call.
func (b *ExternalHostnameBackendApplyConfiguration) WithHostname(value v1.PreciseHostname) *ExternalHostnameBackendApplyConfiguration {
	b.Hostname = &value
	return b
}
