/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apisxv1alpha1 "sigs.k8s.io/gateway-api/apisx/v1alpha1"
	v1 "sigs.k8s.io/gateway-api/applyconfiguration/apis/v1"
)

// ParentBasedSamplingApplyConfiguration represents a declarative configuration of the ParentBasedSampling type for use
// with apply.
//
// ParentBasedSampling defines the sampling behavior when a request has a pre-existing upstream
// trace parent.
//
// Support: Extended
type ParentBasedSamplingApplyConfiguration struct {
	// Mode explicitly controls if parent-based sampling is enabled. Valid values are "Enabled",
	// "Disabled", "ImplementationDefault".
	//
	// In the absence of this field, it defaults to "ImplementationDefault".
	//
	// Support: Extended
	//
	Mode *apisxv1alpha1.ParentBasedSamplingMode `json:"mode,omitempty"`
	// SamplingRate is the sampling rate to apply when parent-based sampling is active.
	//
	// This acts as a downsampling governor. It allows an operator to say: "I want to
	// respect the parent's decision, but only for 50% of those requests". Even if a
	// parent is already marked as "Sampled", this allows the Gateway to apply a secondary
	// filter so that it can respect the parent's intent while still controlling the volume
	// of spans reported.
	//
	// In the absence of this field, it defaults to 100% ({numerator: 100}).
	//
	// Support: Extended
	//
	SamplingRate *v1.FractionApplyConfiguration `json:"samplingRate,omitempty"`
}

// ParentBasedSamplingApplyConfiguration constructs a declarative configuration of the ParentBasedSampling type for use with
// apply.
func ParentBasedSampling() *ParentBasedSamplingApplyConfiguration {
	return &ParentBasedSamplingApplyConfiguration{}
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *ParentBasedSamplingApplyConfiguration) WithMode(value apisxv1alpha1.ParentBasedSamplingMode) *ParentBasedSamplingApplyConfiguration {
	b.Mode = &value
	return b
}

// WithSamplingRate sets the SamplingRate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SamplingRate field is set to the value of the last call.
func (b *ParentBasedSamplingApplyConfiguration) WithSamplingRate(value *v1.FractionApplyConfiguration) *ParentBasedSamplingApplyConfiguration {
	b.SamplingRate = value
	return b
}
