/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "sigs.k8s.io/gateway-api/applyconfiguration/apis/v1"
)

// TelemetryPolicyStatusApplyConfiguration represents a declarative configuration of the TelemetryPolicyStatus type for use
// with apply.
//
// TelemetryPolicyStatus defines the observed state of TelemetryPolicy.
type TelemetryPolicyStatusApplyConfiguration struct {
	// For Policy Status API conventions, see:
	// https://gateway-api.sigs.k8s.io/geps/gep-713/#the-status-stanza-of-policy-objects
	//
	// Ancestors is a list of ancestor resources (specifically Gateway resources)
	// that are associated with the policy, and the status of the policy with
	// respect to each ancestor. When this policy attaches to a parent, the
	// controller that manages the parent and the ancestors MUST add an entry
	// to this list when the controller first sees the policy and SHOULD update
	// the entry as appropriate when the relevant ancestor is modified.
	//
	// For TelemetryPolicy, the ancestor MUST be the Gateway resource
	// referenced in spec.targetRefs.
	//
	// Note also that implementations MUST ONLY populate ancestor status for
	// the Ancestor resources they are responsible for. Implementations MUST
	// use the ControllerName field to uniquely identify the entries in this list
	// that they are responsible for.
	//
	// Note that to achieve this, the list of PolicyAncestorStatus structs
	// MUST be treated as a map with a composite key, made up of the AncestorRef
	// and ControllerName fields combined.
	//
	// A maximum of 16 ancestors will be represented in this list. An empty list
	// means the Policy is not relevant for any ancestors.
	//
	// If this slice is full, implementations MUST NOT add further entries.
	// Instead they MUST consider the policy unimplementable and signal that
	// on any related resources such as the ancestor that would be referenced
	// here.
	Ancestors []v1.PolicyAncestorStatusApplyConfiguration `json:"ancestors,omitempty"`
}

// TelemetryPolicyStatusApplyConfiguration constructs a declarative configuration of the TelemetryPolicyStatus type for use with
// apply.
func TelemetryPolicyStatus() *TelemetryPolicyStatusApplyConfiguration {
	return &TelemetryPolicyStatusApplyConfiguration{}
}

// WithAncestors adds the given value to the Ancestors field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Ancestors field.
func (b *TelemetryPolicyStatusApplyConfiguration) WithAncestors(values ...*v1.PolicyAncestorStatusApplyConfiguration) *TelemetryPolicyStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAncestors")
		}
		b.Ancestors = append(b.Ancestors, *values[i])
	}
	return b
}
