/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "sigs.k8s.io/gateway-api/applyconfiguration/apis/v1"
)

// TelemetryPolicySpecApplyConfiguration represents a declarative configuration of the TelemetryPolicySpec type for use
// with apply.
//
// TelemetryPolicySpec defines the desired state and target of TelemetryPolicy.
//
// Specifying at least one target resource in `targetRefs` is required.
// Tracing behavior can be configured via the `tracing` field.
type TelemetryPolicySpecApplyConfiguration struct {
	// TargetRefs identifies the gateways to which this policy applies (GEP-713).
	//
	// When configured, the telemetry settings defined in this policy are applied
	// uniformly to the referenced resources. In the absence of targetRefs, the policy is
	// invalid and will not be accepted.
	//
	// TargetRefs must be distinct.
	//
	// Support: Core for Gateway
	TargetRefs []v1.NamespacedPolicyTargetReferenceApplyConfiguration `json:"targetRefs,omitempty"`
	// Tracing defines the configuration for distributed tracing.
	//
	// When configured, distributed tracing spans are generated and exported. In the
	// absence of this configuration, tracing behavior is determined by implementation
	// defaults.
	//
	// Support: Extended
	Tracing *TracingConfigApplyConfiguration `json:"tracing,omitempty"`
}

// TelemetryPolicySpecApplyConfiguration constructs a declarative configuration of the TelemetryPolicySpec type for use with
// apply.
func TelemetryPolicySpec() *TelemetryPolicySpecApplyConfiguration {
	return &TelemetryPolicySpecApplyConfiguration{}
}

// WithTargetRefs adds the given value to the TargetRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TargetRefs field.
func (b *TelemetryPolicySpecApplyConfiguration) WithTargetRefs(values ...*v1.NamespacedPolicyTargetReferenceApplyConfiguration) *TelemetryPolicySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTargetRefs")
		}
		b.TargetRefs = append(b.TargetRefs, *values[i])
	}
	return b
}

// WithTracing sets the Tracing field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Tracing field is set to the value of the last call.
func (b *TelemetryPolicySpecApplyConfiguration) WithTracing(value *TracingConfigApplyConfiguration) *TelemetryPolicySpecApplyConfiguration {
	b.Tracing = value
	return b
}
