/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "sigs.k8s.io/gateway-api/applyconfiguration/apis/v1"
)

// TracingProviderApplyConfiguration represents a declarative configuration of the TracingProvider type for use
// with apply.
//
// TracingProvider identifies the tracing backend that receives generated spans.
//
// Support: Core for Service
//
// Support: Implementation-specific for any other resource
type TracingProviderApplyConfiguration struct {
	// BackendRef is a reference to a Kubernetes Service or other supported
	// backend that receives OTLP traces.
	//
	// When configured, tracing data is exported to the referenced backend. If the reference
	// is invalid (e.g., the Service does not exist), the implementation should update the
	// policy's status conditions to indicate an unresolved reference.
	//
	// TLS configuration for the connection to the backend is managed by the referenced
	// object. For example, if the BackendRef points to a Service, a BackendTLSPolicy
	// can be attached to configure TLS. Alternatively, the referenced backend could be a
	// custom resource (e.g., XBackend) that natively manages TLS.
	//
	// Support: Core
	//
	BackendRef *v1.BackendObjectReferenceApplyConfiguration `json:"backendRef,omitempty"`
	// Headers specifies a list of custom headers to be added to the telemetry
	// export requests (e.g., for authentication).
	//
	// Support: Extended
	//
	Headers []v1.HTTPHeaderApplyConfiguration `json:"headers,omitempty"`
}

// TracingProviderApplyConfiguration constructs a declarative configuration of the TracingProvider type for use with
// apply.
func TracingProvider() *TracingProviderApplyConfiguration {
	return &TracingProviderApplyConfiguration{}
}

// WithBackendRef sets the BackendRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackendRef field is set to the value of the last call.
func (b *TracingProviderApplyConfiguration) WithBackendRef(value *v1.BackendObjectReferenceApplyConfiguration) *TracingProviderApplyConfiguration {
	b.BackendRef = value
	return b
}

// WithHeaders adds the given value to the Headers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Headers field.
func (b *TracingProviderApplyConfiguration) WithHeaders(values ...*v1.HTTPHeaderApplyConfiguration) *TracingProviderApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithHeaders")
		}
		b.Headers = append(b.Headers, *values[i])
	}
	return b
}
