/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apisxv1alpha1 "sigs.k8s.io/gateway-api/apisx/v1alpha1"
	v1 "sigs.k8s.io/gateway-api/applyconfiguration/apis/v1"
)

// TracingConfigApplyConfiguration represents a declarative configuration of the TracingConfig type for use
// with apply.
//
// TracingConfig defines the configuration for distributed tracing.
//
// Support: Extended
type TracingConfigApplyConfiguration struct {
	// Mode explicitly controls if tracing is enabled. Valid values are "Enabled", "Disabled",
	// "ImplementationDefault".
	//
	// In the absence of this field, it defaults to "ImplementationDefault".
	//
	// Support: Core (within TelemetryPolicy feature)
	Mode *apisxv1alpha1.TracingMode `json:"mode,omitempty"`
	// Provider specifies the tracing collector or backend endpoint receiving OTLP spans.
	//
	// When configured, spans generated by the Gateway proxy are exported to this destination.
	// In the absence of this field, spans are exported to an implementation-defined default sink.
	//
	// Support: Core (within Tracing feature)
	Provider *TracingProviderApplyConfiguration `json:"provider,omitempty"`
	// SamplingRate specifies the base probability of sampling new traces.
	//
	// The sampling probability is represented as a fraction.
	//
	// For example, a Numerator of 5 and Denominator of 100 represents a 5% sampling rate.
	// * If configured, only the specified percentage of new traces will be initiated.
	// * In the absence of this field, an implementation-defined default is used.
	//
	// <gateway:util:excludeFromCRD>
	// Notes for implementors:
	//
	// Permutations of numerator > denominator are invalid and MUST be rejected via validation.
	// </gateway:util:excludeFromCRD>
	//
	// Support: Extended
	SamplingRate *v1.FractionApplyConfiguration `json:"samplingRate,omitempty"`
	// ParentBasedSampling configures whether to respect the sampling decision of the parent span.
	//
	// * When Mode is "Enabled", the proxy will respect the upstream trace parent's sampling
	// decision.
	// * When Mode is "Disabled" or absent, the proxy applies its own local sampling rate
	// decision.
	//
	// Support: Extended
	//
	// Feature Name: TelemetryPolicyParentBasedSampling
	ParentBasedSampling *ParentBasedSamplingApplyConfiguration `json:"parentBasedSampling,omitempty"`
	// ServiceName is the "service.name" attribute of the OpenTelemetry resource.
	// If absent, the implementation's default service name will be used.
	//
	// Support: Extended
	ServiceName *string `json:"serviceName,omitempty"`
	// SpanName defines a custom name for the OTel span. By default, the name
	// is implementation-specific.
	//
	// Support: Extended
	SpanName *string `json:"spanName,omitempty"`
	// Attributes is a list of custom key-value pairs (or variables) attached to every span.
	//
	// When configured, these attributes are injected into every generated tracing span.
	// In the absence of attributes, only standard proxy-defined attributes are emitted.
	//
	// Support: Extended
	Attributes []AttributeApplyConfiguration `json:"attributes,omitempty"`
}

// TracingConfigApplyConfiguration constructs a declarative configuration of the TracingConfig type for use with
// apply.
func TracingConfig() *TracingConfigApplyConfiguration {
	return &TracingConfigApplyConfiguration{}
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *TracingConfigApplyConfiguration) WithMode(value apisxv1alpha1.TracingMode) *TracingConfigApplyConfiguration {
	b.Mode = &value
	return b
}

// WithProvider sets the Provider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Provider field is set to the value of the last call.
func (b *TracingConfigApplyConfiguration) WithProvider(value *TracingProviderApplyConfiguration) *TracingConfigApplyConfiguration {
	b.Provider = value
	return b
}

// WithSamplingRate sets the SamplingRate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SamplingRate field is set to the value of the last call.
func (b *TracingConfigApplyConfiguration) WithSamplingRate(value *v1.FractionApplyConfiguration) *TracingConfigApplyConfiguration {
	b.SamplingRate = value
	return b
}

// WithParentBasedSampling sets the ParentBasedSampling field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ParentBasedSampling field is set to the value of the last call.
func (b *TracingConfigApplyConfiguration) WithParentBasedSampling(value *ParentBasedSamplingApplyConfiguration) *TracingConfigApplyConfiguration {
	b.ParentBasedSampling = value
	return b
}

// WithServiceName sets the ServiceName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceName field is set to the value of the last call.
func (b *TracingConfigApplyConfiguration) WithServiceName(value string) *TracingConfigApplyConfiguration {
	b.ServiceName = &value
	return b
}

// WithSpanName sets the SpanName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SpanName field is set to the value of the last call.
func (b *TracingConfigApplyConfiguration) WithSpanName(value string) *TracingConfigApplyConfiguration {
	b.SpanName = &value
	return b
}

// WithAttributes adds the given value to the Attributes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Attributes field.
func (b *TracingConfigApplyConfiguration) WithAttributes(values ...*AttributeApplyConfiguration) *TracingConfigApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAttributes")
		}
		b.Attributes = append(b.Attributes, *values[i])
	}
	return b
}
