/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
	apisxv1alpha1 "sigs.k8s.io/gateway-api/apisx/v1alpha1"
	internal "sigs.k8s.io/gateway-api/applyconfiguration/internal"
)

// XTelemetryPolicyApplyConfiguration represents a declarative configuration of the XTelemetryPolicy type for use
// with apply.
//
// TelemetryPolicy is a Direct Attached Policy.
// TelemetryPolicy defines a Direct Attached Policy to configure
// telemetry/observability signals for Gateways.
//
// By applying a TelemetryPolicy, platform operators and developers can ensure
// consistent collection, formatting, and export of observability signals.
//
// <gateway:util:excludeFromCRD>
// Notes for implementors:
//
// TelemetryPolicy is a Direct Attached Policy. Implementing controllers MUST
// adhere to the Policy Attachment guidelines (GEP-713).
//
// Precedence and Conflict Resolution:
// - To prevent complex merging semantics, only a single TelemetryPolicy is
// permitted to apply to a specific Gateway resource at any given time.
// - If multiple TelemetryPolicy resources target the same Gateway, precedence
// MUST be determined using the following criteria, continuing on ties:
// 1. The older policy by creation timestamp takes precedence.
// 2. The policy appearing first in alphabetical order by {namespace}/{name}.
// - For any TelemetryPolicy that does not take precedence, the controller
// MUST set the `Accepted` condition on the policy status to `status: False` with
// Reason `Conflicted`.
//
// Conformance:
// Implementations MUST support the core resource structure and `targetRefs`.
// Support for the tracing block is Extended, but if supported,
// its respective conformance profile must be met.
// </gateway:util:excludeFromCRD>
//
// Support: Extended
type XTelemetryPolicyApplyConfiguration struct {
	v1.TypeMetaApplyConfiguration    `json:""`
	*v1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	// Spec defines the desired state of TelemetryPolicy.
	Spec *TelemetryPolicySpecApplyConfiguration `json:"spec,omitempty"`
	// Status defines the observed state of TelemetryPolicy.
	Status *TelemetryPolicyStatusApplyConfiguration `json:"status,omitempty"`
}

// XTelemetryPolicy constructs a declarative configuration of the XTelemetryPolicy type for use with
// apply.
func XTelemetryPolicy(name, namespace string) *XTelemetryPolicyApplyConfiguration {
	b := &XTelemetryPolicyApplyConfiguration{}
	b.WithName(name)
	b.WithNamespace(namespace)
	b.WithKind("XTelemetryPolicy")
	b.WithAPIVersion("gateway.networking.x-k8s.io/v1alpha1")
	return b
}

// ExtractXTelemetryPolicyFrom extracts the applied configuration owned by fieldManager from
// xTelemetryPolicy for the specified subresource. Pass an empty string for subresource to extract
// the main resource. Common subresources include "status", "scale", etc.
// xTelemetryPolicy must be a unmodified XTelemetryPolicy API object that was retrieved from the Kubernetes API.
// ExtractXTelemetryPolicyFrom provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractXTelemetryPolicyFrom(xTelemetryPolicy *apisxv1alpha1.XTelemetryPolicy, fieldManager string, subresource string) (*XTelemetryPolicyApplyConfiguration, error) {
	b := &XTelemetryPolicyApplyConfiguration{}
	err := managedfields.ExtractInto(xTelemetryPolicy, internal.Parser().Type("io.k8s.sigs.gateway-api.apisx.v1alpha1.XTelemetryPolicy"), fieldManager, b, subresource)
	if err != nil {
		return nil, err
	}
	b.WithName(xTelemetryPolicy.Name)
	b.WithNamespace(xTelemetryPolicy.Namespace)

	b.WithKind("XTelemetryPolicy")
	b.WithAPIVersion("gateway.networking.x-k8s.io/v1alpha1")
	return b, nil
}

// ExtractXTelemetryPolicy extracts the applied configuration owned by fieldManager from
// xTelemetryPolicy. If no managedFields are found in xTelemetryPolicy for fieldManager, a
// XTelemetryPolicyApplyConfiguration is returned with only the Name, Namespace (if applicable),
// APIVersion and Kind populated. It is possible that no managed fields were found for because other
// field managers have taken ownership of all the fields previously owned by fieldManager, or because
// the fieldManager never owned fields any fields.
// xTelemetryPolicy must be a unmodified XTelemetryPolicy API object that was retrieved from the Kubernetes API.
// ExtractXTelemetryPolicy provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractXTelemetryPolicy(xTelemetryPolicy *apisxv1alpha1.XTelemetryPolicy, fieldManager string) (*XTelemetryPolicyApplyConfiguration, error) {
	return ExtractXTelemetryPolicyFrom(xTelemetryPolicy, fieldManager, "")
}

// ExtractXTelemetryPolicyStatus extracts the applied configuration owned by fieldManager from
// xTelemetryPolicy for the status subresource.
func ExtractXTelemetryPolicyStatus(xTelemetryPolicy *apisxv1alpha1.XTelemetryPolicy, fieldManager string) (*XTelemetryPolicyApplyConfiguration, error) {
	return ExtractXTelemetryPolicyFrom(xTelemetryPolicy, fieldManager, "status")
}

func (b XTelemetryPolicyApplyConfiguration) IsApplyConfiguration() {}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *XTelemetryPolicyApplyConfiguration) WithKind(value string) *XTelemetryPolicyApplyConfiguration {
	b.TypeMetaApplyConfiguration.Kind = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *XTelemetryPolicyApplyConfiguration) WithAPIVersion(value string) *XTelemetryPolicyApplyConfiguration {
	b.TypeMetaApplyConfiguration.APIVersion = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *XTelemetryPolicyApplyConfiguration) WithName(value string) *XTelemetryPolicyApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Name = &value
	return b
}

// WithGenerateName sets the GenerateName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateName field is set to the value of the last call.
func (b *XTelemetryPolicyApplyConfiguration) WithGenerateName(value string) *XTelemetryPolicyApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.GenerateName = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *XTelemetryPolicyApplyConfiguration) WithNamespace(value string) *XTelemetryPolicyApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Namespace = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *XTelemetryPolicyApplyConfiguration) WithUID(value types.UID) *XTelemetryPolicyApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.UID = &value
	return b
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *XTelemetryPolicyApplyConfiguration) WithResourceVersion(value string) *XTelemetryPolicyApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.ResourceVersion = &value
	return b
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *XTelemetryPolicyApplyConfiguration) WithGeneration(value int64) *XTelemetryPolicyApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Generation = &value
	return b
}

// WithCreationTimestamp sets the CreationTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTimestamp field is set to the value of the last call.
func (b *XTelemetryPolicyApplyConfiguration) WithCreationTimestamp(value metav1.Time) *XTelemetryPolicyApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.CreationTimestamp = &value
	return b
}

// WithDeletionTimestamp sets the DeletionTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionTimestamp field is set to the value of the last call.
func (b *XTelemetryPolicyApplyConfiguration) WithDeletionTimestamp(value metav1.Time) *XTelemetryPolicyApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionTimestamp = &value
	return b
}

// WithDeletionGracePeriodSeconds sets the DeletionGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionGracePeriodSeconds field is set to the value of the last call.
func (b *XTelemetryPolicyApplyConfiguration) WithDeletionGracePeriodSeconds(value int64) *XTelemetryPolicyApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionGracePeriodSeconds = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *XTelemetryPolicyApplyConfiguration) WithLabels(entries map[string]string) *XTelemetryPolicyApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Labels == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *XTelemetryPolicyApplyConfiguration) WithAnnotations(entries map[string]string) *XTelemetryPolicyApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Annotations == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Annotations[k] = v
	}
	return b
}

// WithOwnerReferences adds the given value to the OwnerReferences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OwnerReferences field.
func (b *XTelemetryPolicyApplyConfiguration) WithOwnerReferences(values ...*v1.OwnerReferenceApplyConfiguration) *XTelemetryPolicyApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOwnerReferences")
		}
		b.ObjectMetaApplyConfiguration.OwnerReferences = append(b.ObjectMetaApplyConfiguration.OwnerReferences, *values[i])
	}
	return b
}

// WithFinalizers adds the given value to the Finalizers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Finalizers field.
func (b *XTelemetryPolicyApplyConfiguration) WithFinalizers(values ...string) *XTelemetryPolicyApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		b.ObjectMetaApplyConfiguration.Finalizers = append(b.ObjectMetaApplyConfiguration.Finalizers, values[i])
	}
	return b
}

func (b *XTelemetryPolicyApplyConfiguration) ensureObjectMetaApplyConfigurationExists() {
	if b.ObjectMetaApplyConfiguration == nil {
		b.ObjectMetaApplyConfiguration = &v1.ObjectMetaApplyConfiguration{}
	}
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *XTelemetryPolicyApplyConfiguration) WithSpec(value *TelemetryPolicySpecApplyConfiguration) *XTelemetryPolicyApplyConfiguration {
	b.Spec = value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *XTelemetryPolicyApplyConfiguration) WithStatus(value *TelemetryPolicyStatusApplyConfiguration) *XTelemetryPolicyApplyConfiguration {
	b.Status = value
	return b
}

// GetKind retrieves the value of the Kind field in the declarative configuration.
func (b *XTelemetryPolicyApplyConfiguration) GetKind() *string {
	return b.TypeMetaApplyConfiguration.Kind
}

// GetAPIVersion retrieves the value of the APIVersion field in the declarative configuration.
func (b *XTelemetryPolicyApplyConfiguration) GetAPIVersion() *string {
	return b.TypeMetaApplyConfiguration.APIVersion
}

// GetName retrieves the value of the Name field in the declarative configuration.
func (b *XTelemetryPolicyApplyConfiguration) GetName() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Name
}

// GetNamespace retrieves the value of the Namespace field in the declarative configuration.
func (b *XTelemetryPolicyApplyConfiguration) GetNamespace() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Namespace
}
