apiVersion: internal.gateway.networking.k8s.io/v1alpha1
kind: GEPDetails
number: 5075
name: Support ClusterTrustBundle as a valid caCertificateRef
status: Experimental
authors:
  - davidesalerno
relationships:
  seeAlso:
    - number: 1897
      name: BackendTLSPolicy - Explicit Backend TLS Connection Configuration
      description: Foundational GEP for BackendTLSPolicy, which this proposal extends for CA certificate references.
    - number: 3787
      name: Support CA Certs from other namespaces in BackendTLSPolicy
      description: Related to CA Certs configuration and validation for BackendTLSPolicy.
