## Used in:
## - site-src/v1alpha1/guides/traffic-splitting.md
apiVersion: networking.x-k8s.io/v1alpha1
kind: HTTPRoute
metadata:
  name: foo-route
  labels:
    gateway: prod-web-gw
spec:
  hostnames:
  - foo.example.com
  rules:
  - forwardTo:
    - serviceName: foo-v1
      port: 8080
      weight: 90
    - serviceName: foo-v2
      port: 8080
      weight: 10
