apiVersion: internal.gateway.networking.k8s.io/v1alpha1
kind: GEPDetails
number: 4359
name: Gateway API Regex
status: Provisional
authors:
  - Stevenjin8
references:
  - https://pubs.opengroup.org/onlinepubs/9799919799/
  - https://github.com/google/re2
  - https://www.pcre.org/
  - https://docs.rs/regex/latest/regex/
  - https://regex101.com
  - https://datatracker.ietf.org/doc/html/rfc9110
  - https://pubs.opengroup.org/onlinepubs/7908799/xbd/locale.html
featureNames:
  - Gateway API Regex
