apiVersion: gateway.networking.k8s.io/v1
date: "2025-05-30T16:25:31-04:00"
gatewayAPIChannel: standard
gatewayAPIVersion: v1.3.0
implementation:
  contact:
  - gateway-api@buoyant.io
  organization: Buoyant
  project: Buoyant Enterprise for Linkerd
  url: https://buoyant.io/
  version: enterprise-2.18
kind: ConformanceReport
mode: default
profiles:
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 1
      Skipped: 0
  name: MESH-GRPC
  summary: Core tests succeeded.
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 3
      Skipped: 0
  name: MESH-HTTP
  summary: Core tests succeeded.
