apiVersion: gateway.networking.k8s.io/v1alpha1
date: "2024-05-07T19:37:36Z"
gatewayAPIVersion: v0.8.1
implementation:
  contact:
  - '@projectcontour/maintainers'
  organization: projectcontour
  project: contour
  url: https://projectcontour.io/
  version: v1.27.3
kind: ConformanceReport
profiles:
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 29
      Skipped: 0
    summary: ""
  extended:
    result: success
    statistics:
      Failed: 0
      Passed: 10
      Skipped: 0
    summary: ""
    supportedFeatures:
    - HTTPRoutePortRedirect
    - HTTPRouteRequestMultipleMirrors
    - HTTPRouteHostRewrite
    - HTTPRouteRequestMirror
    - HTTPRouteQueryParamMatching
    - HTTPRouteMethodMatching
    - HTTPResponseHeaderModification
    - HTTPRoutePathRewrite
    - HTTPRouteSchemeRedirect
    - HTTPRoutePathRedirect
  name: HTTP
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 11
      Skipped: 0
    summary: ""
  name: TLS
