apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  annotations:
    api-approved.kubernetes.io: https://github.com/kubernetes-sigs/gateway-api/pull/3328
    gateway.networking.k8s.io/bundle-version: v1.4.0
    gateway.networking.k8s.io/channel: standard
  name: "gateway-api-safe-upgrades.gateway.networking.k8s.io"
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:   ["apiextensions.k8s.io"]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["*"]
  validations:
    - expression: "object.metadata.annotations['gateway.networking.k8s.io/channel'] != 'experimental'"
      message: "Installing experimental CRDs on top of standard channel CRDs is prohibited by default. Uninstall gateway-api-safe-upgrades.gateway.networking.k8s.io to install experimental CRDs on top of standard channel CRDs."
      reason: Invalid

---

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  annotations:
    api-approved.kubernetes.io: https://github.com/kubernetes-sigs/gateway-api/pull/3328
    gateway.networking.k8s.io/bundle-version: v1.4.0
    gateway.networking.k8s.io/channel: standard
  name: gateway-api-safe-upgrades.gateway.networking.k8s.io
spec:
  policyName: gateway-api-safe-upgrades.gateway.networking.k8s.io
  validationActions: [Deny]
  matchResources:
    objectSelector: {}
