apiVersion: internal.gateway.networking.k8s.io/v1alpha1
kind: GEPDetails
number: 2644
name: TCPRoute - Add support for routing based on a TCP port
status: Experimental
authors:
  - zac-nixon
  - rikatz
  - youngnick
relationships:
  seeAlso:
    - number: 2643
      name: TLS based passthrough Route / TLSRoute
    - number: 2645
      name: UDPRoute
    - number: 735
      name: TCP and UDP addresses matching
references:
  - https://www.ietf.org/rfc/rfc9293.txt
featureNames:
  - TCPRoute
changelog:
  - 2026/May/18 (rikatz) - Add request flow, conflict management, conformance scenarios, and feature names
