apiVersion: gateway.networking.kubernetes.io/v1
kind: ImplementationListDetails
organization: fluxcd
project: flagger
url: http://github.com/fluxcd/flagger
fullName: "Flagger"
description: |
  [Flagger][flagger] is a progressive delivery tool that automates the release process for applications running on Kubernetes.

  Flagger can be used to automate canary deployments and A/B testing using Gateway API. You can refer to [this tutorial][flagger-tutorial] to use Flagger with any implementation of Gateway API.

  [flagger]: https://flagger.app
  [flagger-tutorial]: https://docs.flagger.app/tutorials/gatewayapi-progressive-delivery
