apiVersion: gateway.networking.kubernetes.io/v1
kind: ImplementationListDetails
organization: traefik
project: traefik
fullName: Traefik Proxy
description: |
  Traefik Proxy supports the Gateway API specification, check the [Kubernetes Gateway Provider Documentation][traefik-proxy-gateway-api-doc] for more information on how to deploy and use it.

  For help and support with Traefik Proxy, [create an issue][traefik-proxy-issue-new] or ask for help in the [Traefik Labs Community Forum][traefiklabs-community-forum].

  [traefik-proxy]:https://traefik.io
  [traefik-proxy-gateway-api-doc]:https://doc.traefik.io/traefik/v3.7/reference/install-configuration/providers/kubernetes/kubernetes-gateway
  [traefik-proxy-issue-new]:https://github.com/traefik/traefik/issues/new/choose
  [traefiklabs-community-forum]:https://community.traefik.io/c/traefik/traefik-v3/21
