kind: BackendPolicy
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: my-app
spec:
  backendRefs:
    - name: my-service
      group: ""
      kind: Service
  tls:
    certificateAuthorityRef: 
      name: my-app-ca
      group: ""
      kind: Secret
    options: {}
