apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: routability-bad-constant
spec:
  gatewayClassName: acme-lb
  infrastructure:
    routability: NotAValidValue
  listeners:
  - name: http
    protocol: HTTP
    port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: routability-missing-slash-and-suffix
spec:
  gatewayClassName: acme-lb
  infrastructure:
    routability: invalid.prefix.requires.a.slash
  listeners:
  - name: http
    protocol: HTTP
    port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: routability-missing-suffix
spec:
  gatewayClassName: acme-lb
  infrastructure:
    routability: invalid.prefix.requires.a.slash.and.text/
  listeners:
  - name: http
    protocol: HTTP
    port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: routability-vendor-suffix-invalid-character
spec:
  gatewayClassName: acme-lb
  infrastructure:
    routability: some.vendor.prefix/bad!!
  listeners:
  - name: http
    protocol: HTTP
    port: 80
