apiVersion: batch/v1
kind: Job
metadata:
  name: gateway-api-crd-list
  namespace: default
  labels:
    app: gateway-api-crd-installer
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app: gateway-api-crd-installer
    spec:
      serviceAccountName: gateway-api-crd-installer
      restartPolicy: OnFailure
      containers:
      - name: lister
        image: gateway-api-crd-installer:local
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "/scripts/install.sh", "-l"]
