apiVersion: networking.x-k8s.io/v1alpha1
kind: BackendPolicy
metadata:
  name: my-app
spec:
  backendRefs:
    - name: my-service
      group: core
      kind: Service
  tls:
    certificateAuthorityRef: 
      name: my-app-ca
      group: core
      kind: Secret
    options: {}
