## Used in:
## - site-src/v1alpha1/guides/tls.md
apiVersion: networking.x-k8s.io/v1alpha1
kind: BackendPolicy
metadata:
  name: my-app
  annotations:
    networking.x-k8s.io/app-protocol: https
spec:
  backendRefs:
  - name: my-service
    group: core
    kind: Service
    port: 443
  tls:
    certificateAuthorityRef:
      name: my-cluster-ca
      group: core
      kind: Secret
    options: {}
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  selector:
    app: my-service
---
apiVersion: networking.x-k8s.io/v1alpha1
kind: HTTPRoute
metadata:
  name: my-service-route
spec:
  hostnames:
  - "foo.com"
  rules:
  - matches:
    - path:
        type: Prefix
        value: /
    forwardTo:
    - serviceName: my-service
      port: 443
