apiVersion: gateway.networking.kubernetes.io/v1
kind: ImplementationListDetails
organization: aws
project: aws-application-networking-k8s
url: https://github.com/aws/aws-application-networking-k8s
fullName: "Amazon Elastic Kubernetes Service"
description: |
  [Amazon Elastic Kubernetes Service (EKS)][eks] is a managed service that you can use to run Kubernetes on AWS without needing to install, operate, and maintain your own Kubernetes control plane or nodes. EKS's implementation of the Gateway API is through [AWS Gateway API Controller][eks-gateway] which provisions [Amazon VPC Lattice][vpc-lattice] Resources for gateway(s), HTTPRoute(s) in EKS clusters.

  [eks]:https://docs.aws.amazon.com/eks/latest/userguide/what-is-eks.html
  [eks-gateway]:https://github.com/aws/aws-application-networking-k8s
  [vpc-lattice]:https://aws.amazon.com/vpc/lattice/
