apiVersion: gateway.networking.k8s.io/v1alpha1
date: "2024-06-26T11:55:06+02:00"
gatewayAPIChannel: experimental
gatewayAPIVersion: v1.1.0
implementation:
  contact:
    - '@traefik/maintainers'
  organization: traefik
  project: traefik
  url: https://traefik.io/
  version: v3.1.0
kind: ConformanceReport
mode: default
profiles:
  - core:
      result: success
      statistics:
        Failed: 0
        Passed: 33
        Skipped: 0
    extended:
      result: success
      statistics:
        Failed: 0
        Passed: 9
        Skipped: 0
      supportedFeatures:
        - GatewayPort8080
        - HTTPRouteHostRewrite
        - HTTPRouteMethodMatching
        - HTTPRoutePathRedirect
        - HTTPRoutePathRewrite
        - HTTPRoutePortRedirect
        - HTTPRouteQueryParamMatching
        - HTTPRouteSchemeRedirect
      unsupportedFeatures:
        - GatewayHTTPListenerIsolation
        - GatewayStaticAddresses
        - HTTPRouteBackendRequestHeaderModification
        - HTTPRouteBackendTimeout
        - HTTPRouteParentRefPort
        - HTTPRouteRequestMirror
        - HTTPRouteRequestMultipleMirrors
        - HTTPRouteRequestTimeout
        - HTTPRouteResponseHeaderModification
    name: GATEWAY-HTTP
    summary: Core tests succeeded. Extended tests succeeded.
