apiVersion: gateway.networking.k8s.io/v1alpha1
date: "2024-06-07T06:33:39Z"
gatewayAPIChannel: experimental
gatewayAPIVersion: v1.1.0
implementation:
  contact:
    - https://github.com/cilium/community/blob/main/roles/Maintainers.md
  organization: cilium
  project: cilium
  url: github.com/cilium/cilium
  version: v1.16.0
kind: ConformanceReport
mode: default
profiles:
  - core:
      result: success
      statistics:
        Failed: 0
        Passed: 33
        Skipped: 0
    extended:
      result: success
      statistics:
        Failed: 0
        Passed: 16
        Skipped: 0
      supportedFeatures:
        - GatewayHTTPListenerIsolation
        - GatewayPort8080
        - HTTPRouteBackendRequestHeaderModification
        - HTTPRouteBackendTimeout
        - HTTPRouteHostRewrite
        - HTTPRouteMethodMatching
        - HTTPRoutePathRedirect
        - HTTPRoutePathRewrite
        - HTTPRoutePortRedirect
        - HTTPRouteQueryParamMatching
        - HTTPRouteRequestMirror
        - HTTPRouteRequestMultipleMirrors
        - HTTPRouteRequestTimeout
        - HTTPRouteResponseHeaderModification
        - HTTPRouteSchemeRedirect
      unsupportedFeatures:
        - GatewayStaticAddresses
        - HTTPRouteParentRefPort
    name: GATEWAY-HTTP
    summary: Core tests succeeded. Extended tests succeeded.
  - core:
      result: success
      statistics:
        Failed: 0
        Passed: 11
        Skipped: 0
    name: GATEWAY-TLS
    summary: Core tests succeeded.
  - core:
      result: success
      statistics:
        Failed: 0
        Passed: 3
        Skipped: 0
    extended:
      result: success
      statistics:
        Failed: 0
        Passed: 2
        Skipped: 0
      supportedFeatures:
        - HTTPRouteBackendRequestHeaderModification
        - HTTPRouteBackendTimeout
        - HTTPRouteHostRewrite
        - HTTPRouteMethodMatching
        - HTTPRoutePathRedirect
        - HTTPRoutePathRewrite
        - HTTPRoutePortRedirect
        - HTTPRouteQueryParamMatching
        - HTTPRouteRequestMirror
        - HTTPRouteRequestMultipleMirrors
        - HTTPRouteRequestTimeout
        - HTTPRouteResponseHeaderModification
        - HTTPRouteSchemeRedirect
        - MeshClusterIPMatching
      unsupportedFeatures:
        - HTTPRouteParentRefPort
        - MeshConsumerRoute
    name: MESH-HTTP
    summary: Core tests succeeded. Extended tests succeeded.
  - core:
      result: success
      statistics:
        Failed: 0
        Passed: 12
        Skipped: 0
    name: GATEWAY-GRPC
    summary: Core tests succeeded.
