apiVersion: gateway.networking.k8s.io/v1alpha1
date: '2023-11-03T05:34:35Z'
gatewayAPIVersion: v1.0.0
implementation:
  contact:
    - 'https://github.com/cilium/community/blob/main/roles/Maintainers.md'
  organization: cilium
  project: cilium
  url: github.com/cilium/cilium
  version: v1.15.0-pre.3
kind: ConformanceReport
profiles:
  - core:
      result: success
      statistics:
        Failed: 0
        Passed: 29
        Skipped: 0
      summary: ''
    extended:
      result: success
      statistics:
        Failed: 0
        Passed: 12
        Skipped: 0
      summary: ''
      supportedFeatures:
        - HTTPRouteBackendTimeout
        - HTTPRouteHostRewrite
        - HTTPRouteMethodMatching
        - HTTPRouteParentRefPort
        - HTTPRoutePathRedirect
        - HTTPRoutePathRewrite
        - HTTPRoutePortRedirect
        - HTTPRouteQueryParamMatching
        - HTTPRouteRequestMirror
        - HTTPRouteRequestMultipleMirrors
        - HTTPRouteRequestTimeout
        - HTTPRouteResponseHeaderModification
        - HTTPRouteSchemeRedirect
    name: HTTP
  - core:
      result: success
      statistics:
        Failed: 0
        Passed: 10
        Skipped: 0
      summary: ''
    name: TLS
