apiVersion: gateway.networking.k8s.io/v1
date: "2026-07-20T20:02:46Z"
gatewayAPIChannel: experimental
gatewayAPIVersion: v1.6.1
implementation:
  contact:
  - github.com/kgateway-dev/kgateway/issues/new/choose
  organization: kgateway-dev
  project: kgateway
  url: github.com/kgateway-dev/kgateway
  version: v2.4.0-rc.1
kind: ConformanceReport
mode: default
profiles:
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 37
      Skipped: 0
  extended:
    result: success
    statistics:
      Failed: 0
      Passed: 56
      Skipped: 0
    supportedFeatures:
    - BackendTLSPolicy
    - BackendTLSPolicySANValidation
    - GatewayAddressEmpty
    - GatewayBackendClientCertificate
    - GatewayFrontendClientCertificateValidation
    - GatewayFrontendClientCertificateValidationInsecureFallback
    - GatewayHTTPListenerIsolation
    - GatewayInfrastructurePropagation
    - GatewayPort8080
    - GatewayStaticAddresses
    - HTTPRoute303RedirectStatusCode
    - HTTPRoute307RedirectStatusCode
    - HTTPRoute308RedirectStatusCode
    - HTTPRouteBackendProtocolH2C
    - HTTPRouteBackendProtocolWebSocket
    - HTTPRouteBackendRequestHeaderModification
    - HTTPRouteBackendTimeout
    - HTTPRouteCORS
    - HTTPRouteDestinationPortMatching
    - HTTPRouteHostRewrite
    - HTTPRouteMethodMatching
    - HTTPRouteNamedRouteRule
    - HTTPRouteParentRefPort
    - HTTPRoutePathRedirect
    - HTTPRoutePathRewrite
    - HTTPRoutePortRedirect
    - HTTPRouteQueryParamMatching
    - HTTPRouteRequestMirror
    - HTTPRouteRequestMultipleMirrors
    - HTTPRouteRequestPercentageMirror
    - HTTPRouteRequestTimeout
    - HTTPRouteResponseHeaderModification
    - HTTPRouteRetry
    - HTTPRouteRetryBackendTimeout
    - HTTPRouteRetryConnectionError
    - HTTPRouteSchemeRedirect
    - ListenerSet
    unsupportedFeatures:
    - GatewayHTTPSListenerDetectMisdirectedRequests
  name: GATEWAY-HTTP
  summary: Core tests succeeded. Extended tests succeeded.
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 15
      Skipped: 0
  extended:
    result: success
    statistics:
      Failed: 0
      Passed: 10
      Skipped: 0
    supportedFeatures:
    - GatewayAddressEmpty
    - GatewayBackendClientCertificate
    - GatewayFrontendClientCertificateValidation
    - GatewayFrontendClientCertificateValidationInsecureFallback
    - GatewayHTTPListenerIsolation
    - GatewayInfrastructurePropagation
    - GatewayPort8080
    - GatewayStaticAddresses
    - ListenerSet
    unsupportedFeatures:
    - GatewayHTTPSListenerDetectMisdirectedRequests
  name: GATEWAY-GRPC
  summary: Core tests succeeded. Extended tests succeeded.
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 19
      Skipped: 0
  extended:
    result: success
    statistics:
      Failed: 0
      Passed: 10
      Skipped: 0
    supportedFeatures:
    - GatewayAddressEmpty
    - GatewayBackendClientCertificate
    - GatewayFrontendClientCertificateValidation
    - GatewayFrontendClientCertificateValidationInsecureFallback
    - GatewayHTTPListenerIsolation
    - GatewayInfrastructurePropagation
    - GatewayPort8080
    - GatewayStaticAddresses
    - ListenerSet
    - TCPRoute
    unsupportedFeatures:
    - GatewayHTTPSListenerDetectMisdirectedRequests
  name: GATEWAY-TCP
  summary: Core tests succeeded. Extended tests succeeded.
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 20
      Skipped: 0
  extended:
    result: success
    statistics:
      Failed: 0
      Passed: 15
      Skipped: 0
    supportedFeatures:
    - GatewayAddressEmpty
    - GatewayBackendClientCertificate
    - GatewayFrontendClientCertificateValidation
    - GatewayFrontendClientCertificateValidationInsecureFallback
    - GatewayHTTPListenerIsolation
    - GatewayInfrastructurePropagation
    - GatewayPort8080
    - GatewayStaticAddresses
    - ListenerSet
    - TLSRouteModeMixed
    - TLSRouteModeTerminate
    unsupportedFeatures:
    - GatewayHTTPSListenerDetectMisdirectedRequests
  name: GATEWAY-TLS
  summary: Core tests succeeded. Extended tests succeeded.
succeededProvisionalTests:
- GRPCRouteNamedRule
- GatewayInfrastructure
- GatewayOptionalAddressValue
- HTTPRoute303Redirect
- HTTPRoute307Redirect
- HTTPRoute308Redirect
- HTTPRouteNamedRule
- HTTPRouteRequestPercentageMirror
- TCPRouteInvalidBackendRefNonexistent
- TCPRouteInvalidCrossNamespaceBackendRef
- TCPRouteInvalidNonTCPListener
- TCPRouteParentRefAttachAll
- TCPRouteParentRefPortAndSectionName
- TCPRouteReferenceGrant
- TCPRouteWeightedRouting
- TLSRouteMixedTerminationSameNamespace
- TLSRouteTerminateSimpleSameNamespace
