kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1alpha2
metadata:
  name: duplicate-query-match
spec:
  rules:
  - matches:
    - queryParams:
      - name: foo
        value: bar
      - name: foo
        value: bar
