apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: hostname-tcp
spec:
  gatewayClassName: example
  listeners:
  - name: example
    hostname: example.com
    protocol: TCP
    port: 80
