apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: hostname-udp
spec:
  gatewayClassName: example
  listeners:
  - name: example
    hostname: example.com
    protocol: UDP
    port: 80
