apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: duplicate-listeners
spec:
  gatewayClassName: example
  listeners:
  - name: foo
    protocol: HTTPS
    port: 443
    tls:
      mode: Passthrough
