apiVersion: gateway.networking.k8s.io/v1alpha1
date: "2023-12-14T20:16:14Z"
gatewayAPIVersion: v1.0.0
implementation:
  contact:
  - https://github.com/nginx/nginx-gateway-fabric/discussions/new/choose
  organization: nginx
  project: nginx-gateway-fabric
  url: https://github.com/nginx/nginx-gateway-fabric
  version: v1.1.0
kind: ConformanceReport
profiles:
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 29
      Skipped: 0
    summary: ""
  extended:
    result: success
    statistics:
      Failed: 0
      Passed: 4
      Skipped: 0
    summary: ""
    supportedFeatures:
    - HTTPRouteSchemeRedirect
    - HTTPRouteMethodMatching
    - HTTPRouteQueryParamMatching
    - HTTPRoutePortRedirect
    unsupportedFeatures:
    - HTTPRoutePathRedirect
    - HTTPRoutePathRewrite
    - HTTPRouteHostRewrite
    - HTTPRouteRequestMirror
    - HTTPResponseHeaderModification
  name: HTTP
