apiVersion: gateway.networking.k8s.io/v1alpha1
date: "2024-10-24T11:45:25Z"
gatewayAPIChannel: experimental
gatewayAPIVersion: v1.1.0
implementation:
  contact:
    - https://www.airlock.com/en/contact
  organization: airlock
  project: microgateway
  url: https://github.com/airlock/microgateway
  version: v4.4.0
kind: ConformanceReport
mode: default
profiles:
  - core:
      result: success
      statistics:
        Failed: 0
        Passed: 33
        Skipped: 0
    extended:
      result: success
      statistics:
        Failed: 0
        Passed: 5
        Skipped: 0
      supportedFeatures:
        - GatewayPort8080
        - HTTPRouteMethodMatching
        - HTTPRouteParentRefPort
        - HTTPRouteQueryParamMatching
      unsupportedFeatures:
        - GatewayHTTPListenerIsolation
        - GatewayStaticAddresses
        - HTTPRouteBackendRequestHeaderModification
        - HTTPRouteBackendTimeout
        - HTTPRouteHostRewrite
        - HTTPRoutePathRedirect
        - HTTPRoutePathRewrite
        - HTTPRoutePortRedirect
        - HTTPRouteRequestMirror
        - HTTPRouteRequestMultipleMirrors
        - HTTPRouteRequestTimeout
        - HTTPRouteResponseHeaderModification
        - HTTPRouteSchemeRedirect
    name: GATEWAY-HTTP
    summary: Core tests succeeded. Extended tests succeeded.
