/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	apisv1 "sigs.k8s.io/gateway-api/apis/v1"
)

// ClusterTrustBundleObjectRefApplyConfiguration represents a declarative configuration of the ClusterTrustBundleObjectRef type for use
// with apply.
//
// ClusterTrustBundleObjectRef identifies a ClusterTrustBundle.
//
// The Group defaults to "certificates.k8s.io" and the Kind defaults to
// "ClusterTrustBundle", so users only need to specify the name.
//
// This type is intended exclusively for cluster-scoped ClusterTrustBundle
// resources. The absence of a Namespace field is intentional and correct -
// it MUST NOT be used with namespace-scoped resources.
//
// A ReferenceGrant is not required because ClusterTrustBundle is cluster-scoped
// and has no target namespace.
type ClusterTrustBundleObjectRefApplyConfiguration struct {
	// Group is the group of the referent.
	//
	// Defaults to "certificates.k8s.io".
	Group *apisv1.Group `json:"group,omitempty"`
	// Kind is the kind of the referent.
	//
	// Defaults to "ClusterTrustBundle".
	Kind *apisv1.Kind `json:"kind,omitempty"`
	// Name is the name of the referent.
	Name *apisv1.ObjectName `json:"name,omitempty"`
}

// ClusterTrustBundleObjectRefApplyConfiguration constructs a declarative configuration of the ClusterTrustBundleObjectRef type for use with
// apply.
func ClusterTrustBundleObjectRef() *ClusterTrustBundleObjectRefApplyConfiguration {
	return &ClusterTrustBundleObjectRefApplyConfiguration{}
}

// WithGroup sets the Group field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Group field is set to the value of the last call.
func (b *ClusterTrustBundleObjectRefApplyConfiguration) WithGroup(value apisv1.Group) *ClusterTrustBundleObjectRefApplyConfiguration {
	b.Group = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *ClusterTrustBundleObjectRefApplyConfiguration) WithKind(value apisv1.Kind) *ClusterTrustBundleObjectRefApplyConfiguration {
	b.Kind = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ClusterTrustBundleObjectRefApplyConfiguration) WithName(value apisv1.ObjectName) *ClusterTrustBundleObjectRefApplyConfiguration {
	b.Name = &value
	return b
}
