/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// HTTPDirectResponseFilterApplyConfiguration represents a declarative configuration of the HTTPDirectResponseFilter type for use
// with apply.
//
// HTTPDirectResponseFilter defines a filter that replies to the matched request
// directly from the gateway, without forwarding to any backend.
//
// A rule using this filter MUST NOT have backendRefs set.
//
// Support: Extended
//
// Feature Name: HTTPRouteDirectResponse
//
// <gateway:experimental>
type HTTPDirectResponseFilterApplyConfiguration struct {
	// StatusCode is the HTTP status code to be used in the direct response.
	StatusCode *int `json:"statusCode,omitempty"`
	// Body is the content of the HTTP response body to be returned.
	Body *HTTPDirectResponseBodyApplyConfiguration `json:"body,omitempty"`
}

// HTTPDirectResponseFilterApplyConfiguration constructs a declarative configuration of the HTTPDirectResponseFilter type for use with
// apply.
func HTTPDirectResponseFilter() *HTTPDirectResponseFilterApplyConfiguration {
	return &HTTPDirectResponseFilterApplyConfiguration{}
}

// WithStatusCode sets the StatusCode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StatusCode field is set to the value of the last call.
func (b *HTTPDirectResponseFilterApplyConfiguration) WithStatusCode(value int) *HTTPDirectResponseFilterApplyConfiguration {
	b.StatusCode = &value
	return b
}

// WithBody sets the Body field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Body field is set to the value of the last call.
func (b *HTTPDirectResponseFilterApplyConfiguration) WithBody(value *HTTPDirectResponseBodyApplyConfiguration) *HTTPDirectResponseFilterApplyConfiguration {
	b.Body = value
	return b
}
