/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	apisv1 "sigs.k8s.io/gateway-api/apis/v1"
)

// HTTPRouteMatchApplyConfiguration represents a declarative configuration of the HTTPRouteMatch type for use
// with apply.
//
// HTTPRouteMatch defines the predicate used to match requests to a given
// action. Multiple match types are ANDed together, i.e. the match will
// evaluate to true only if all conditions are satisfied.
//
// For example, the match below will match a HTTP request only if its path
// starts with `/foo` AND it contains the `version: v1` header:
//
// ```
// match:
//
// path:
// value: "/foo"
// headers:
// - name: "version"
// value "v1"
//
// ```
//
// Multiple HTTP methods can be matched in a single match using the Methods
// field. When Methods is specified, Method must also be specified and must
// match Methods[0]:
//
// ```
// match:
//
// path:
// type: PathPrefix
// value: /api/
// method: GET
// methods:
// - GET
// - POST
// - PUT
//
// ```
//
// <gateway:experimental:validation:XValidation:message="method must be specified and match methods[0] when methods is set",rule="!has(self.methods) || size(self.methods) == 0 || (has(self.method) && self.method == self.methods[0])">
type HTTPRouteMatchApplyConfiguration struct {
	// Path specifies a HTTP request path matcher. If this field is not
	// specified, a default prefix match on the "/" path is provided.
	Path *HTTPPathMatchApplyConfiguration `json:"path,omitempty"`
	// Headers specifies HTTP request header matchers. Multiple match values are
	// ANDed together, meaning, a request must match all the specified headers
	// to select the route.
	Headers []HTTPHeaderMatchApplyConfiguration `json:"headers,omitempty"`
	// QueryParams specifies HTTP query parameter matchers. Multiple match
	// values are ANDed together, meaning, a request must match all the
	// specified query parameters to select the route.
	//
	// Support: Extended
	QueryParams []HTTPQueryParamMatchApplyConfiguration `json:"queryParams,omitempty"`
	// Method specifies HTTP method matcher.
	// When specified, this route will be matched only if the request has the
	// specified method.
	//
	// When Methods is specified, Method must also be specified and must match
	// Methods[0].
	//
	// Support: Extended
	Method *apisv1.HTTPMethod `json:"method,omitempty"`
	// Methods specifies HTTP method matchers.
	// When specified, this route will be matched if the request has any of the
	// specified methods.
	//
	// When this field is specified, Method must also be specified and must match
	// Methods[0].
	//
	// Support: Extended
	//
	// <gateway:experimental>
	Methods []apisv1.HTTPMethod `json:"methods,omitempty"`
}

// HTTPRouteMatchApplyConfiguration constructs a declarative configuration of the HTTPRouteMatch type for use with
// apply.
func HTTPRouteMatch() *HTTPRouteMatchApplyConfiguration {
	return &HTTPRouteMatchApplyConfiguration{}
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *HTTPRouteMatchApplyConfiguration) WithPath(value *HTTPPathMatchApplyConfiguration) *HTTPRouteMatchApplyConfiguration {
	b.Path = value
	return b
}

// WithHeaders adds the given value to the Headers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Headers field.
func (b *HTTPRouteMatchApplyConfiguration) WithHeaders(values ...*HTTPHeaderMatchApplyConfiguration) *HTTPRouteMatchApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithHeaders")
		}
		b.Headers = append(b.Headers, *values[i])
	}
	return b
}

// WithQueryParams adds the given value to the QueryParams field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the QueryParams field.
func (b *HTTPRouteMatchApplyConfiguration) WithQueryParams(values ...*HTTPQueryParamMatchApplyConfiguration) *HTTPRouteMatchApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithQueryParams")
		}
		b.QueryParams = append(b.QueryParams, *values[i])
	}
	return b
}

// WithMethod sets the Method field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Method field is set to the value of the last call.
func (b *HTTPRouteMatchApplyConfiguration) WithMethod(value apisv1.HTTPMethod) *HTTPRouteMatchApplyConfiguration {
	b.Method = &value
	return b
}

// WithMethods adds the given value to the Methods field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Methods field.
func (b *HTTPRouteMatchApplyConfiguration) WithMethods(values ...apisv1.HTTPMethod) *HTTPRouteMatchApplyConfiguration {
	for i := range values {
		b.Methods = append(b.Methods, values[i])
	}
	return b
}
