/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ListenerFiltersApplyConfiguration represents a declarative configuration of the ListenerFilters type for use
// with apply.
//
// ListenerFilters is the container for pre-routing filter lists on a
// Listener.
//
// Today only the request phase (Requests) is defined. In the future
// a connection-oriented phase (Connection) may be added.
type ListenerFiltersApplyConfiguration struct {
	// Implementations MUST execute the filters in the exact order they
	// appear here and MUST NOT reorder them. If an implementation can
	// not implement the filters in the order they are specified, the
	// implementation MUST set the "Accepted" Listener condition to "false"
	// with the "InvalidListenerFilterOrder" reason.
	//
	// Requests only apply to connections with a visible HTTP stream
	// and metadata (Protocol=HTTP, or Protocol=HTTPS with TLS
	// terminated at the Gateway).
	//
	// Requests may mutate inputs that route matching consumes
	// (path, request headers, method, computed metadata), with the
	// explicit exception of the `Host` and `:authority` headers, which
	// implementations MUST reject any attempt to modify. Implementations
	// MUST evaluate route matching exactly once after the last
	// ListenerFilter has run.
	//
	// Requests MUST NOT be interpreted as changing which Listener
	// handles the request. Listener selection is decided from inputs
	// the client committed to before any pre-routing filter runs: TLS
	// SNI (for HTTPS) or the request's initial Host header (for HTTP).
	// Because filters cannot modify Host or :authority, the input to
	// cleartext-HTTP Listener selection cannot change; Listener
	// selection therefore does not need to be re-evaluated after
	// pre-routing filters run, and MUST NOT be.
	Requests []ListenerFilterApplyConfiguration `json:"requests,omitempty"`
}

// ListenerFiltersApplyConfiguration constructs a declarative configuration of the ListenerFilters type for use with
// apply.
func ListenerFilters() *ListenerFiltersApplyConfiguration {
	return &ListenerFiltersApplyConfiguration{}
}

// WithRequests adds the given value to the Requests field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Requests field.
func (b *ListenerFiltersApplyConfiguration) WithRequests(values ...*ListenerFilterApplyConfiguration) *ListenerFiltersApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithRequests")
		}
		b.Requests = append(b.Requests, *values[i])
	}
	return b
}
