/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	apisv1 "sigs.k8s.io/gateway-api/apis/v1"
)

// SessionPersistenceApplyConfiguration represents a declarative configuration of the SessionPersistence type for use
// with apply.
//
// SessionPersistence defines the desired state of SessionPersistence.
type SessionPersistenceApplyConfiguration struct {
	// AbsoluteTimeout defines the absolute timeout of the persistent
	// session. Once the AbsoluteTimeout duration has elapsed, the
	// session becomes invalid.
	//
	// Support: Extended
	AbsoluteTimeout *apisv1.Duration `json:"absoluteTimeout,omitempty"`
	// Type defines the type of session persistence such as through
	// the use of a header or cookie. Defaults to cookie based session
	// persistence.
	//
	// Support: Core for "Cookie" type
	//
	// Support: Extended for "Header" type
	Type *apisv1.SessionPersistenceType `json:"type,omitempty"`
	// Cookie provides configuration settings that are specific
	// to cookie-based session persistence.
	//
	// Support: Core
	Cookie *CookieConfigApplyConfiguration `json:"cookie,omitempty"`
	// Header provides configuration settings that are specific
	// to header-based session persistence.
	//
	// Support: Extended
	Header *HeaderConfigApplyConfiguration `json:"header,omitempty"`
}

// SessionPersistenceApplyConfiguration constructs a declarative configuration of the SessionPersistence type for use with
// apply.
func SessionPersistence() *SessionPersistenceApplyConfiguration {
	return &SessionPersistenceApplyConfiguration{}
}

// WithAbsoluteTimeout sets the AbsoluteTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AbsoluteTimeout field is set to the value of the last call.
func (b *SessionPersistenceApplyConfiguration) WithAbsoluteTimeout(value apisv1.Duration) *SessionPersistenceApplyConfiguration {
	b.AbsoluteTimeout = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *SessionPersistenceApplyConfiguration) WithType(value apisv1.SessionPersistenceType) *SessionPersistenceApplyConfiguration {
	b.Type = &value
	return b
}

// WithCookie sets the Cookie field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cookie field is set to the value of the last call.
func (b *SessionPersistenceApplyConfiguration) WithCookie(value *CookieConfigApplyConfiguration) *SessionPersistenceApplyConfiguration {
	b.Cookie = value
	return b
}

// WithHeader sets the Header field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Header field is set to the value of the last call.
func (b *SessionPersistenceApplyConfiguration) WithHeader(value *HeaderConfigApplyConfiguration) *SessionPersistenceApplyConfiguration {
	b.Header = value
	return b
}
