apiVersion: gateway.networking.k8s.io/v1
date: "2026-04-25T02:48:14Z"
gatewayAPIChannel: experimental
gatewayAPIVersion: v1.5.1
implementation:
  contact:
  - '@istio/maintainers'
  organization: istio
  project: istio
  url: https://istio.io/
  version: "1.30"
kind: ConformanceReport
mode: default
profiles:
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 33
      Skipped: 0
  extended:
    result: partial
    skippedTests:
    - BackendTLSPolicy
    - BackendTLSPolicyConflictResolution
    - BackendTLSPolicyObservedGenerationBump
    - GatewayBackendClientCertificateFeature
    - GatewayFrontendClientCertificateValidation
    - GatewayFrontendClientCertificateValidationInsecureFallback
    - GatewayFrontendInvalidDefaultClientCertificateValidation
    - GatewayInvalidFrontendClientCertificateValidation
    - GatewayInvalidTLSBackendConfiguration
    - GatewayWithAttachedRoutesWithPort8080
    - HTTPRoute303Redirect
    - HTTPRoute307Redirect
    - HTTPRoute308Redirect
    - HTTPRouteCORS
    - HTTPRouteHTTPSListenerDetectMisdirectedRequests
    - ListenerSetAllowedNamespaceNone
    - ListenerSetAllowedNamespaceSame
    - ListenerSetAllowedNamespaceSelector
    - ListenerSetAllowedRoutesNamespaces
    - ListenerSetDefaultNotAllowed
    - ListenerSetHTTPRouting
    - ListenerSetHostnameConflict
    - ListenerSetProtocolConflict
    - ListenerSetReferenceGrant
    statistics:
      Failed: 0
      Passed: 30
      Skipped: 24
    supportedFeatures:
    - BackendTLSPolicy
    - BackendTLSPolicySANValidation
    - GatewayAddressEmpty
    - GatewayBackendClientCertificate
    - GatewayFrontendClientCertificateValidation
    - GatewayFrontendClientCertificateValidationInsecureFallback
    - GatewayHTTPListenerIsolation
    - GatewayHTTPSListenerDetectMisdirectedRequests
    - GatewayInfrastructurePropagation
    - GatewayPort8080
    - GatewayStaticAddresses
    - HTTPRoute303RedirectStatusCode
    - HTTPRoute307RedirectStatusCode
    - HTTPRoute308RedirectStatusCode
    - HTTPRouteBackendProtocolH2C
    - HTTPRouteBackendProtocolWebSocket
    - HTTPRouteBackendRequestHeaderModification
    - HTTPRouteBackendTimeout
    - HTTPRouteCORS
    - HTTPRouteDestinationPortMatching
    - HTTPRouteHostRewrite
    - HTTPRouteMethodMatching
    - HTTPRouteNamedRouteRule
    - HTTPRouteParentRefPort
    - HTTPRoutePathRedirect
    - HTTPRoutePathRewrite
    - HTTPRoutePortRedirect
    - HTTPRouteQueryParamMatching
    - HTTPRouteRequestMirror
    - HTTPRouteRequestMultipleMirrors
    - HTTPRouteRequestPercentageMirror
    - HTTPRouteRequestTimeout
    - HTTPRouteResponseHeaderModification
    - HTTPRouteSchemeRedirect
    - ListenerSet
  name: GATEWAY-HTTP
  summary: Core tests succeeded. Extended tests partially succeeded with 24 test skips.
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 13
      Skipped: 0
  extended:
    result: partial
    skippedTests:
    - ListenerSetAllowedNamespaceNone
    - ListenerSetAllowedNamespaceSame
    - ListenerSetAllowedNamespaceSelector
    - ListenerSetDefaultNotAllowed
    - ListenerSetHostnameConflict
    - ListenerSetProtocolConflict
    - ListenerSetReferenceGrant
    statistics:
      Failed: 0
      Passed: 3
      Skipped: 7
    supportedFeatures:
    - GatewayAddressEmpty
    - GatewayBackendClientCertificate
    - GatewayFrontendClientCertificateValidation
    - GatewayFrontendClientCertificateValidationInsecureFallback
    - GatewayHTTPListenerIsolation
    - GatewayHTTPSListenerDetectMisdirectedRequests
    - GatewayInfrastructurePropagation
    - GatewayPort8080
    - GatewayStaticAddresses
    - ListenerSet
  name: GATEWAY-GRPC
  summary: Core tests succeeded. Extended tests partially succeeded with 7 test skips.
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 18
      Skipped: 0
  extended:
    result: partial
    skippedTests:
    - ListenerSetAllowedNamespaceNone
    - ListenerSetAllowedNamespaceSame
    - ListenerSetAllowedNamespaceSelector
    - ListenerSetAllowedRoutesSupportedKinds
    - ListenerSetDefaultNotAllowed
    - ListenerSetHostnameConflict
    - ListenerSetProtocolConflict
    - ListenerSetReferenceGrant
    statistics:
      Failed: 0
      Passed: 7
      Skipped: 8
    supportedFeatures:
    - GatewayAddressEmpty
    - GatewayBackendClientCertificate
    - GatewayFrontendClientCertificateValidation
    - GatewayFrontendClientCertificateValidationInsecureFallback
    - GatewayHTTPListenerIsolation
    - GatewayHTTPSListenerDetectMisdirectedRequests
    - GatewayInfrastructurePropagation
    - GatewayPort8080
    - GatewayStaticAddresses
    - ListenerSet
    - TLSRouteModeMixed
    - TLSRouteModeTerminate
  name: GATEWAY-TLS
  summary: Core tests succeeded. Extended tests partially succeeded with 8 test skips.
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 7
      Skipped: 0
  extended:
    result: success
    statistics:
      Failed: 0
      Passed: 7
      Skipped: 0
    supportedFeatures:
    - MeshConsumerRoute
    - MeshHTTPRouteBackendRequestHeaderModification
    - MeshHTTPRouteNamedRouteRule
    - MeshHTTPRouteQueryParamMatching
    - MeshHTTPRouteRedirectPath
    - MeshHTTPRouteRedirectPort
    - MeshHTTPRouteRewritePath
    - MeshHTTPRouteSchemeRedirect
    unsupportedFeatures:
    - MeshClusterIPMatching
  name: MESH-HTTP
  summary: Core tests succeeded. Extended tests succeeded.
succeededProvisionalTests:
- GRPCRouteNamedRule
- GatewayInfrastructure
- GatewayOptionalAddressValue
- HTTPRouteNamedRule
- HTTPRouteRequestPercentageMirror
- MeshHTTPRouteNamedRule
- TLSRouteMixedTerminationSameNamespace
- TLSRouteTerminateSimpleSameNamespace
