apiVersion: gateway.networking.kubernetes.io/v1
kind: ImplementationListDetails
organization: airlock
project: microgateway
url: https://github.com/airlock/microgateway
fullName: "Airlock Microgateway"
description: |
  [Airlock Microgateway][airlock-microgateway] is a Kubernetes-native security solution that extends the routing capabilities of the Gateway API with WAAP (Web Application and API Protection) features and identity-aware proxying.
  It filters requests using deny rules against known attacks (OWASP Top 10), along with header filtering, JSON parsing, OpenAPI specification enforcement, GraphQL schema validation, and antivirus scanning via ICAP.
  Authentication can be enforced via client certificates, JWT, or OIDC with step-up authentication for MFA, with support for OAuth 2.0 Token Introspection and Token Exchange. Airlock Microgateway is certified for Red Hat OpenShift, and built-in Grafana dashboards provide real-time reporting on system health, traffic and threats.

  [airlock-microgateway]:https://www.airlock.com/en/secure-access-hub/components/microgateway
